import axios from "axios";
import { getTeamAbbr, round1, round3 } from "../utils/formatters";

// Static data files generated by GitHub Actions (served from same origin)
const BASE = import.meta.env.BASE_URL || "/";
const dataUrl = (path) => `${BASE}data/${path}`;

const staticFetch = (path) => axios.get(dataUrl(path)).then((r) => r.data);

// MLB Stats API called directly from browser (no backend needed, free & fast)
const mlbApi = axios.create({
  baseURL: "https://statsapi.mlb.com/api/v1",
  timeout: 15000,
});

// ---- Static data (generated daily) ----
export const fetchRoster = (teamId) => staticFetch(`teams/${getTeamAbbr(teamId)}/roster.json`);

export const fetchSchedule = (teamId) => staticFetch(`teams/${getTeamAbbr(teamId)}/schedule.json`);

export const fetchStandings = async () => {
  // Fetch live from MLB API for freshest standings
  try {
    const season = new Date().getFullYear();
    const resp = await mlbApi.get("/standings", { params: { season, sportId: 1, leagueId: "103,104" } });
    const divisions = [];
    for (const record of resp.data?.records || []) {
      const div = record.division || {};
      const teams = (record.teamRecords || []).map((tr) => {
        const t = tr.team || {};
        return {
          id: t.id, name: t.name || "", abbreviation: t.abbreviation || "",
          wins: tr.wins || 0, losses: tr.losses || 0,
          winPct: tr.winningPercentage || ".000",
          gamesBack: tr.gamesBack || "-",
          streakCode: tr.streak?.streakCode || "",
          logoUrl: `https://www.mlbstatic.com/team-logos/${t.id}.svg`,
        };
      });
      divisions.push({ divisionId: div.id, divisionName: div.name || "", teams });
    }
    return divisions;
  } catch {
    // Fallback to static data if API fails
    return staticFetch("standings.json");
  }
};

export const fetchPlayerDetail = (playerId) =>
  staticFetch(`players/${playerId}/info.json`).then((d) => d.detail);

export const fetchPlayerStats = (playerId) =>
  staticFetch(`players/${playerId}/info.json`);

export const fetchPlayerAdvanced = (playerId) =>
  staticFetch(`players/${playerId}/advanced.json`).catch(() => ({}));

export const fetchPlayerArsenal = async (playerId) => {
  // Try static pre-generated data first
  try {
    const data = await staticFetch(`players/${playerId}/arsenal.json`);
    if (data?.pitches?.length) return data;
  } catch {}

  // Fallback: MLB Stats API (works for any pitcher, our team or opponent)
  const year = new Date().getFullYear();
  for (const season of [year, year - 1]) {
    try {
      const resp = await mlbApi.get(`/people/${playerId}/stats`, {
        params: { stats: "pitchArsenal", season, group: "pitching" },
      });
      const splits = resp.data?.stats?.[0]?.splits || [];
      if (splits.length) return formatMlbArsenal(splits);
    } catch {}
  }
  return { pitches: [], totalPitches: 0 };
};

function formatMlbArsenal(splits) {
  const PITCH_NAMES = {
    FF: "4-Seam Fastball", SI: "Sinker", FC: "Cutter", SL: "Slider",
    CU: "Curveball", KC: "Knuckle Curve", CH: "Changeup", FS: "Splitter",
    SV: "Sweeper", ST: "Sweeping Curve", KN: "Knuckleball",
  };
  const pitches = splits.map((s) => {
    const stat = s.stat || {};
    const code = stat.type?.code || s.stat?.pitchType?.code || "";
    return {
      pitchType: code,
      pitchName: PITCH_NAMES[code] || stat.type?.description || code,
      usagePct: stat.percentage != null ? round1(stat.percentage * 100) : null,
      avgVelo: stat.averageSpeed != null ? round1(stat.averageSpeed) : null,
      avgSpin: stat.averageSpin != null ? Math.round(stat.averageSpin) : null,
      whiffRate: stat.swingAndMiss != null ? round1(stat.swingAndMiss * 100) : null,
      baAgainst: stat.battingAverage != null ? stat.battingAverage : null,
      count: stat.totalPitches || 0,
      horzBreak: stat.horizontalBreak != null ? round1(stat.horizontalBreak) : null,
      vertBreak: stat.verticalBreak != null ? round1(stat.verticalBreak) : null,
    };
  }).filter((p) => p.pitchType);
  pitches.sort((a, b) => (b.usagePct || 0) - (a.usagePct || 0));
  return { pitches, totalPitches: pitches.reduce((sum, p) => sum + (p.count || 0), 0) };
}

export const fetchPlayerDominance = (playerId) =>
  Promise.resolve({}); // Not pre-generated yet, can add later

export const fetchSprayChart = (playerId, homeTeam) =>
  staticFetch(`players/${playerId}/spray/${homeTeam}.json`).catch(() => ({ hits: [], summary: {} }));

export const fetchVenues = () => staticFetch("venues.json");

export const fetchPlayoffOdds = () =>
  Promise.resolve({ teams: [] }); // FanGraphs scraping removed, can add to generate script later

export const fetchMeta = () => staticFetch("meta.json").catch(() => null);

// ---- Live data (MLB Stats API, called directly from browser) ----
export const fetchTodayGame = async (teamId) => {
  const today = new Date();
  const endDate = new Date(today);
  endDate.setDate(endDate.getDate() + 14);

  const fmt = (d) => d.toISOString().split("T")[0];

  try {
    // Check today first
    const todayResp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1, teamId, date: fmt(today),
        hydrate: "team,linescore,probablePitcher", gameType: "R",
      },
    });

    const todayGames = todayResp.data.dates?.[0]?.games || [];

    // Live or scheduled game today
    const liveOrScheduled = todayGames.find((g) =>
      ["In Progress", "Scheduled", "Pre-Game", "Warmup"].includes(g.status?.detailedState)
    );
    if (liveOrScheduled) return formatGame(liveOrScheduled, true);

    // Final game today - also find next game
    const finalGame = todayGames.find((g) => g.status?.detailedState === "Final");

    // Get upcoming games
    const futureResp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1, teamId, startDate: fmt(today), endDate: fmt(endDate),
        hydrate: "team,linescore,probablePitcher", gameType: "R",
      },
    });

    const allDates = futureResp.data.dates || [];
    let nextGame = null;
    for (const dateEntry of allDates) {
      const gameDate = new Date(dateEntry.date + "T00:00:00");
      if (gameDate <= today) continue;
      if (dateEntry.games?.length) {
        nextGame = dateEntry.games[0];
        break;
      }
    }

    if (finalGame) {
      const result = formatGame(finalGame, false);
      result.nextGame = nextGame ? formatGame(nextGame, true) : null;
      return result;
    }

    if (nextGame) return formatGame(nextGame, true);
    return { noGame: true, message: "No games scheduled in the next 14 days." };
  } catch (e) {
    console.error("Failed to fetch game:", e);
    return { noGame: true, message: "Unable to load game data." };
  }
};

export const fetchHotPlayers = () =>
  Promise.resolve([]); // Requires pybaseball, not available client-side

export const fetchBvP = async (batterId, pitcherId) => {
  try {
    const bvp = await staticFetch(`players/${batterId}/bvp.json`);
    return bvp[String(pitcherId)] || { pa: 0 };
  } catch {
    return { pa: 0 };
  }
};

export const fetchPitchTypeMatchup = () => Promise.resolve([]);

export const fetchParkHistory = async (teamId) => {
  try {
    const abbr = getTeamAbbr(teamId);
    const schedule = await staticFetch(`teams/${abbr}/schedule.json`);
    const finals = schedule.filter((g) => g.status === "Final");
    if (!finals.length) return null; // Season hasn't started
    const wins = finals.filter((g) => {
      const isHome = Number(g.home.id) === Number(teamId);
      return isHome ? g.home.isWinner : g.away.isWinner;
    }).length;
    const losses = finals.length - wins;
    return { wins, losses, winPct: finals.length > 0 ? round3(wins / finals.length) : null, recentGames: [] };
  } catch {
    return null;
  }
};

export const fetchPriorMatchups = async (team1, team2) => {
  try {
    const abbr = getTeamAbbr(team1);
    const schedule = await staticFetch(`teams/${abbr}/schedule.json`);
    const matchups = schedule.filter((g) => {
      return g.status === "Final" && (Number(g.away.id) === Number(team2) || Number(g.home.id) === Number(team2));
    });
    if (!matchups.length) return null; // Season hasn't started
    const wins = matchups.filter((g) => {
      const isHome = Number(g.home.id) === Number(team1);
      return isHome ? g.home.isWinner : g.away.isWinner;
    }).length;
    return {
      games: matchups.map((g) => ({
        gamePk: g.gamePk, date: g.gameDate,
        homeAbbr: g.home.abbreviation, awayAbbr: g.away.abbreviation,
        homeScore: g.home.score, awayScore: g.away.score,
        won: Number(g.home.id) === Number(team1) ? g.home.isWinner : g.away.isWinner,
      })),
      record: { wins, losses: matchups.length - wins },
    };
  } catch {
    return { games: [], record: { wins: 0, losses: 0 } };
  }
};

// ---- New Features: Live MLB API calls ----

// 3. Transaction feed (roster moves, IL, trades)
export const fetchTransactions = async (teamId) => {
  try {
    const end = new Date();
    const start = new Date();
    start.setDate(start.getDate() - 30);
    const fmt = (d) => d.toISOString().split("T")[0];
    const resp = await mlbApi.get("/transactions", {
      params: { teamId, startDate: fmt(start), endDate: fmt(end) },
    });
    return (resp.data?.transactions || []).map((t) => ({
      id: t.id,
      date: t.date,
      type: t.typeCode,
      typeDesc: t.typeDesc,
      description: t.description,
      player: t.person ? { id: t.person.id, name: t.person.fullName } : null,
    })).slice(0, 10);
  } catch {
    return [];
  }
};

// 4. Player game log (last 10 games)
export const fetchPlayerGameLog = async (playerId, group = "hitting") => {
  const year = new Date().getFullYear();
  for (const season of [year, year - 1]) {
    try {
      const resp = await mlbApi.get(`/people/${playerId}/stats`, {
        params: { stats: "gameLog", season, group },
      });
      const splits = resp.data?.stats?.[0]?.splits || [];
      if (splits.length) {
        return splits.slice(-10).reverse().map((s) => ({
          date: s.date,
          opponent: s.opponent?.abbreviation || s.opponent?.name?.split(" ").pop() || "",
          isHome: s.isHome,
          isWin: s.isWin,
          stat: s.stat,
        }));
      }
    } catch {}
  }
  return [];
};

// 5. Win probability for a game
export const fetchWinProbability = async (gamePk) => {
  try {
    const resp = await mlbApi.get(`/game/${gamePk}/winProbability`);
    return (resp.data || []).map((wp) => ({
      atBatIndex: wp.atBatIndex,
      homeProb: wp.homeTeamWinProbability,
      awayProb: wp.awayTeamWinProbability,
      probAdded: wp.homeTeamWinProbabilityAdded,
      leverage: wp.leverageIndex,
    }));
  } catch {
    return [];
  }
};

// 8. Team hot/cold players (our team, last 7 days game logs)
export const fetchTeamHotCold = async (teamId) => {
  try {
    const abbr = getTeamAbbr(teamId);
    const roster = await staticFetch(`teams/${abbr}/roster.json`);
    const batters = roster.filter((p) => p.position.type !== "Pitcher");
    const year = new Date().getFullYear();
    const results = [];

    for (const batter of batters.slice(0, 15)) {
      try {
        const resp = await mlbApi.get(`/people/${batter.id}/stats`, {
          params: { stats: "gameLog", season: year, group: "hitting" },
        });
        const splits = resp.data?.stats?.[0]?.splits || [];
        const last7 = splits.slice(-7);
        if (last7.length < 3) continue;

        let ab = 0, hits = 0, hr = 0, rbi = 0;
        for (const g of last7) {
          ab += g.stat.atBats || 0;
          hits += g.stat.hits || 0;
          hr += g.stat.homeRuns || 0;
          rbi += g.stat.rbi || 0;
        }
        if (ab < 10) continue;
        const avg = hits / ab;
        const ops = parseFloat(last7[0]?.stat?.ops || "0");

        results.push({
          id: batter.id,
          name: batter.fullName,
          position: batter.position.abbreviation,
          games: last7.length, ab, hits, hr, rbi,
          avg: Math.round(avg * 1000) / 1000,
          photoUrl: batter.photoUrl,
          isHot: avg >= .300,
          isCold: avg < .150,
        });
      } catch {}
    }

    results.sort((a, b) => b.avg - a.avg);
    return {
      hot: results.filter((r) => r.isHot).slice(0, 5),
      cold: results.filter((r) => r.isCold).slice(0, 3),
    };
  } catch {
    return { hot: [], cold: [] };
  }
};

// 9. League leaders
export const fetchLeagueLeaders = async () => {
  try {
    const year = new Date().getFullYear();
    const categories = ["homeRuns", "battingAverage", "earnedRunAverage", "strikeouts", "stolenBases"];
    const results = {};

    for (const cat of categories) {
      try {
        const resp = await mlbApi.get("/stats/leaders", {
          params: { leaderCategories: cat, season: year, sportId: 1, limit: 5 },
        });
        const leaders = resp.data?.leagueLeaders?.[0]?.leaders || [];
        results[cat] = leaders.map((l) => ({
          rank: l.rank,
          value: l.value,
          player: { id: l.person?.id, name: l.person?.fullName },
          team: l.team?.abbreviation || "",
          teamId: l.team?.id,
        }));
      } catch {}
    }
    return results;
  } catch {
    return {};
  }
};

// 10. Upcoming series (next 4 games with probable pitchers)
export const fetchUpcomingSeries = async (teamId) => {
  try {
    const today = new Date();
    const end = new Date();
    end.setDate(end.getDate() + 10);
    const fmt = (d) => d.toISOString().split("T")[0];

    const resp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1, teamId,
        startDate: fmt(today), endDate: fmt(end),
        hydrate: "team,probablePitcher", gameType: "R",
      },
    });

    const games = [];
    for (const dateEntry of resp.data?.dates || []) {
      for (const g of dateEntry.games || []) {
        if (g.status?.detailedState === "Final") continue;
        const away = g.teams?.away || {};
        const home = g.teams?.home || {};
        games.push({
          gamePk: g.gamePk,
          gameDate: g.gameDate,
          venue: g.venue?.name || "",
          away: {
            id: away.team?.id, abbreviation: away.team?.abbreviation || "",
            probablePitcher: extractPitcher(away.probablePitcher),
            logoUrl: `https://www.mlbstatic.com/team-logos/${away.team?.id}.svg`,
          },
          home: {
            id: home.team?.id, abbreviation: home.team?.abbreviation || "",
            probablePitcher: extractPitcher(home.probablePitcher),
            logoUrl: `https://www.mlbstatic.com/team-logos/${home.team?.id}.svg`,
          },
        });
        if (games.length >= 4) break;
      }
      if (games.length >= 4) break;
    }
    return games;
  } catch {
    return [];
  }
};

// ---- Helpers ----
function formatGame(g, isNext) {
  const away = g.teams?.away || {};
  const home = g.teams?.home || {};
  const at = away.team || {};
  const ht = home.team || {};

  return {
    gamePk: g.gamePk,
    gameDate: g.gameDate || "",
    status: g.status?.detailedState || "",
    isNextGame: isNext,
    venue: { id: g.venue?.id, name: g.venue?.name || "" },
    away: {
      id: at.id, name: at.name || "", abbreviation: at.abbreviation || "",
      score: away.score,
      probablePitcher: extractPitcher(away.probablePitcher),
      logoUrl: `https://www.mlbstatic.com/team-logos/${at.id}.svg`,
    },
    home: {
      id: ht.id, name: ht.name || "", abbreviation: ht.abbreviation || "",
      score: home.score,
      probablePitcher: extractPitcher(home.probablePitcher),
      logoUrl: `https://www.mlbstatic.com/team-logos/${ht.id}.svg`,
    },
  };
}

function extractPitcher(p) {
  if (!p) return null;
  return {
    id: p.id,
    fullName: p.fullName || "",
    photoUrl: `https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/${p.id}/headshot/67/current`,
  };
}
