import axios from "axios";
import { getTeamAbbr, round1, round3 } from "../utils/formatters";

// Static data files generated by GitHub Actions (served from same origin)
const BASE = import.meta.env.BASE_URL || "/";
const dataUrl = (path) => `${BASE}data/${path}`;

const staticFetch = (path) => axios.get(dataUrl(path)).then((r) => r.data);

// MLB API uses several distinct `detailedState` values for games that are
// over and won't resume — collapse them all to "Final" so downstream UI
// (ScheduleView, TodayGame, Scoreboard, MatchupView, etc.) treats them
// uniformly. Includes:
//   "Final"           — standard 9+ inning result
//   "Game Over"       — interim status briefly emitted between last out and final
//   "Completed Early" — rain-shortened, suspended-then-final, etc.
//   "Final: Tied"     — extremely rare ties (extra-inning rule changes, etc.)
// Anything else (Postponed, Cancelled, Suspended, Scheduled, In Progress…)
// passes through unchanged.
const TERMINAL_DETAILED_STATES = new Set([
  "Final",
  "Game Over",
  "Completed Early",
  "Final: Tied",
]);
export const isTerminalDetailedState = (s) => {
  if (!s) return false;
  if (TERMINAL_DETAILED_STATES.has(s)) return true;
  // MLB also emits forms like "Completed Early: Rain" — match the prefix.
  return s.startsWith("Completed Early") || s.startsWith("Final:");
};
export const normalizeStatus = (s) => (isTerminalDetailedState(s) ? "Final" : (s || ""));

// MLB API sometimes marks isScoringPlay=false when runs score on mid-AB events
// (e.g. pickoff errors, wild pitches, passed balls during a strikeout).
// Check runners array as fallback.
const didRunScore = (play) =>
  play.about?.isScoringPlay ||
  (play.runners || []).some((r) => r.details?.isScoringEvent);

// Build description for plays where the scoring event is a mid-AB runner event
// (the result.description won't mention the run scoring in these cases)
const scoringDescription = (play) => {
  const desc = play.result?.description || "";
  if (play.about?.isScoringPlay) return desc;
  const scoredRunners = (play.runners || [])
    .filter((r) => r.details?.isScoringEvent)
    .map((r) => r.details?.runner?.fullName || "");
  if (!scoredRunners.length) return desc;
  const event = (play.runners || [])
    .find((r) => r.details?.isScoringEvent)?.details?.event || "";
  const eventDesc = event.replace(/_/g, " ");
  const scored = scoredRunners.join(", ");
  return desc
    ? `${scored} scores on ${eventDesc.toLowerCase()}. ${desc}`
    : `${scored} scores on ${eventDesc.toLowerCase()}.`;
};

// MLB Stats API called directly from browser (no backend needed, free & fast)
const mlbApi = axios.create({
  baseURL: "https://statsapi.mlb.com/api/v1",
  timeout: 15000,
});

// ---- Static data (generated daily) ----
export const fetchRoster = async (teamId) => {
  const season = new Date().getFullYear();
  const resp = await mlbApi.get(`/teams/${teamId}/roster`, {
    params: { rosterType: "active", season },
  });
  return (resp.data.roster || []).map((entry) => {
    const p = entry.person || {};
    const pos = entry.position || {};
    return {
      id: p.id,
      fullName: p.fullName || "",
      jerseyNumber: entry.jerseyNumber || "",
      position: {
        code: pos.code || "",
        name: pos.name || "",
        type: pos.type || "",
        abbreviation: pos.abbreviation || "",
      },
      status: entry.status?.description || "Active",
      photoUrl: `https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/${p.id}/headshot/67/current`,
    };
  });
};

// Full season schedule straight from the MLB Stats API. Previously we
// served a static per-team schedule.json generated once daily + merged
// in a last-7-days live scores call — which meant non-recently-updated
// static files showed stale records for games older than a week.
// Going live-only means every game's status + score is always current
// and we don't need to regenerate static per-team files.
//
// Returns an array matching the legacy static shape so existing
// consumers (ScheduleView, etc.) need no changes.
export const fetchSchedule = async (teamId) => {
  try {
    const season = new Date().getFullYear();
    const resp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1,
        teamId,
        season,
        gameType: "R",
        hydrate: "team,linescore,venue,probablePitcher",
      },
    });
    // MLB returns postponed games TWICE — once on the original date with
    // detailedState="Postponed" and a rescheduleDate, and again on the
    // replay date with detailedState="Final" and rescheduledFrom set.
    // Dedupe by gamePk, keeping the row that best represents truth:
    //   Final > In Progress > Postponed/Cancelled/Suspended > Scheduled
    // That way, replayed games collapse onto their actual played date, and
    // still-postponed games (no replay yet) keep their Postponed row with
    // the rescheduleDate the UI can surface.
    const STATUS_PRIORITY = {
      "Final": 0,
      "Game Over": 0,
      "Completed Early": 0,
      "Final: Tied": 0,
      "In Progress": 1,
      "Suspended": 2,
      "Postponed": 3,
      "Cancelled": 3,
      "Delayed": 4,
      "Delayed Start": 4,
      "Warmup": 5,
      "Pre-Game": 5,
      "Scheduled": 6,
    };
    const prioFor = (s) => {
      if (s == null) return 99;
      if (STATUS_PRIORITY[s] !== undefined) return STATUS_PRIORITY[s];
      // Match the same terminal-state prefixes normalizeStatus does.
      if (isTerminalDetailedState(s)) return 0;
      return 99;
    };
    const byPk = new Map();
    for (const date of resp.data?.dates || []) {
      for (const g of date.games || []) {
        const prev = byPk.get(g.gamePk);
        const prevPrio = prev ? prioFor(prev.status?.detailedState) : 99;
        const thisPrio = prioFor(g.status?.detailedState);
        if (!prev || thisPrio < prevPrio) byPk.set(g.gamePk, g);
      }
    }
    const games = [];
    for (const g of byPk.values()) {
      const away = g.teams?.away || {};
      const home = g.teams?.home || {};
      const at = away.team || {};
      const ht = home.team || {};
      const detailedState = g.status?.detailedState || "";
      const status = normalizeStatus(detailedState);
      const isFinal = status === "Final";
      const awayScore = away.score ?? null;
      const homeScore = home.score ?? null;
      games.push({
        gamePk: g.gamePk,
        gameDate: g.gameDate,
        status,
        detailedState,                            // raw MLB state for UI badges
        rescheduleDate: g.rescheduleDate || null, // set when still postponed
        rescheduledFrom: g.rescheduledFrom || null, // set on the replay row
        venue: {
          id: g.venue?.id,
          name: g.venue?.name || "",
        },
        away: {
          id: at.id,
          name: at.name || "",
          abbreviation: at.abbreviation || "",
          score: awayScore,
          isWinner: isFinal && awayScore != null && homeScore != null
            ? awayScore > homeScore
            : false,
          probablePitcher: away.probablePitcher
            ? { id: away.probablePitcher.id, fullName: away.probablePitcher.fullName }
            : null,
          logoUrl: at.id ? `https://www.mlbstatic.com/team-logos/team-cap-on-dark/${at.id}.svg` : "",
        },
        home: {
          id: ht.id,
          name: ht.name || "",
          abbreviation: ht.abbreviation || "",
          score: homeScore,
          isWinner: isFinal && awayScore != null && homeScore != null
            ? homeScore > awayScore
            : false,
          probablePitcher: home.probablePitcher
            ? { id: home.probablePitcher.id, fullName: home.probablePitcher.fullName }
            : null,
          logoUrl: ht.id ? `https://www.mlbstatic.com/team-logos/team-cap-on-dark/${ht.id}.svg` : "",
        },
      });
    }
    // Re-sort by gameDate since dedupe may have picked later-dated rows.
    games.sort((a, b) => new Date(a.gameDate) - new Date(b.gameDate));
    return games;
  } catch {
    // Fallback to static JSON if API call fails (offline, rate-limited, etc.)
    try { return await staticFetch(`teams/${getTeamAbbr(teamId)}/schedule.json`); }
    catch { return []; }
  }
};

// Kept as a no-op stub so any remaining import references don't break.
// ScheduleView no longer needs the "merge last 7 days over static" flow
// now that fetchSchedule returns live-fresh data for the whole season.
export const fetchLiveSchedule = async () => [];

export const fetchStandings = async () => {
  // Fetch live from MLB API for freshest standings
  try {
    const season = new Date().getFullYear();
    const resp = await mlbApi.get("/standings", {
      params: {
        season, sportId: 1, leagueId: "103,104",
        hydrate: "team,league,division,records",
      },
    });
    const divisions = [];
    for (const record of resp.data?.records || []) {
      const div = record.division || {};
      const lg = record.league || {};
      const teams = (record.teamRecords || []).map((tr) => {
        const t = tr.team || {};
        // splitRecords holds home/away/lastTen/etc. as { wins, losses, type, pct }
        const splits = tr.records?.splitRecords || [];
        const getSplit = (type) => splits.find((s) => s.type === type) || { wins: 0, losses: 0 };
        const home = getSplit("home");
        const away = getSplit("away");
        const lastTen = getSplit("lastTen");
        return {
          id: t.id,
          name: t.name || "",
          abbreviation: t.abbreviation || "",
          wins: tr.wins || 0,
          losses: tr.losses || 0,
          winPct: tr.winningPercentage || ".000",
          gamesBack: tr.gamesBack || "-",
          wildCardGamesBack: tr.wildCardGamesBack || "-",
          leagueGamesBack: tr.leagueGamesBack || "-",
          divisionRank: tr.divisionRank ? Number(tr.divisionRank) : null,
          leagueRank: tr.leagueRank ? Number(tr.leagueRank) : null,
          wildCardRank: tr.wildCardRank ? Number(tr.wildCardRank) : null,
          streakCode: tr.streak?.streakCode || "",
          runsScored: tr.runsScored ?? 0,
          runsAllowed: tr.runsAllowed ?? 0,
          runDifferential: tr.runDifferential ?? 0,
          clinchIndicator: tr.clinchIndicator || "",
          eliminationNumber: tr.eliminationNumber || "",
          homeRecord: `${home.wins}-${home.losses}`,
          awayRecord: `${away.wins}-${away.losses}`,
          lastTenRecord: `${lastTen.wins}-${lastTen.losses}`,
          leagueId: lg.id,
          leagueName: lg.name || "",
          divisionId: div.id,
          divisionName: div.name || "",
          logoUrl: `https://www.mlbstatic.com/team-logos/team-cap-on-dark/${t.id}.svg`,
        };
      });
      divisions.push({
        divisionId: div.id,
        divisionName: div.name || "",
        leagueId: lg.id,
        leagueName: lg.name || "",
        teams,
      });
    }
    return divisions;
  } catch {
    // Fallback to static data if API fails
    return staticFetch("standings.json");
  }
};



export const fetchPlayerStats = async (playerId) => {
  // Strategy: static JSON is daily-regenerated and covers bio / roster /
  // historical stats well, but its CURRENT-SEASON stats are typically
  // stale (up to 24h behind). For accurate season stats we always
  // overlay a fresh MLB API fetch on top.
  const season = new Date().getFullYear();

  // 1. Start with static file if we have it (fast + complete bio).
  let staticData = null;
  try {
    staticData = await staticFetch(`players/${playerId}/info.json`);
  } catch { /* expected fallback for non-roster / opponent players */ }

  // 2. In parallel with #3 below, get the MLB detail record if we don't
  //    already have static. (Opponents and non-roster guys need this.)
  const detailPromise = staticData?.detail?.id
    ? Promise.resolve({ data: null })  // already have it from static
    : mlbApi.get(`/people/${playerId}`, { params: { hydrate: "currentTeam" } });

  // 3. ALWAYS fetch current-season stats live. Static version is up to
  //    24h stale after each nightly regen; MLB updates immediately
  //    after each game.
  const [detailResp, hittingResp, pitchingResp] = await Promise.all([
    detailPromise,
    mlbApi.get(`/people/${playerId}/stats`, { params: { stats: "season", season, group: "hitting" } }).catch(() => ({})),
    mlbApi.get(`/people/${playerId}/stats`, { params: { stats: "season", season, group: "pitching" } }).catch(() => ({})),
  ]);

  // Assemble detail: prefer static (more complete) but fill gaps from API.
  let detail = staticData?.detail;
  if (!detail || !detail.id) {
    const p = detailResp.data?.people?.[0];
    if (!p) throw new Error("Player not found");
    detail = {
      id: p.id,
      fullName: p.fullName || "",
      firstName: p.firstName || "",
      lastName: p.lastName || "",
      primaryNumber: p.primaryNumber || "",
      birthDate: p.birthDate || "",
      age: p.currentAge,
      height: p.height || "",
      weight: p.weight,
      batSide: p.batSide?.code || "",
      pitchHand: p.pitchHand?.code || "",
      primaryPosition: p.primaryPosition?.abbreviation || "",
      mlbDebutDate: p.mlbDebutDate || "",
      currentTeam: p.currentTeam?.name || "",
      currentTeamId: p.currentTeam?.id || null,
      photoUrl: `https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/${p.id}/headshot/67/current`,
    };
  }

  // Determine hitter vs pitcher using detail, then pick the corresponding
  // LIVE stats response.
  const isPitcher = detail.primaryPosition === "P";
  const group = isPitcher ? "pitching" : "hitting";
  const statsResp = isPitcher ? pitchingResp : hittingResp;
  const splits = statsResp.data?.stats?.[0]?.splits || [];
  const currentStats = splits[0]?.stat || {};

  // If MLB returns nothing for current season (rare — off-season / retired),
  // fall back to static's stored stats or previous season.
  let finalStats = currentStats;
  let prevStats = {};
  let prevSeason = season - 1;
  if (!Object.keys(currentStats).length) {
    // Prefer static's cached stats if they exist.
    const staticStats = staticData?.stats?.stats || {};
    if (Object.keys(staticStats).length) {
      finalStats = staticStats;
      prevStats = staticData?.stats?.prevStats || {};
      prevSeason = staticData?.stats?.prevSeason || season - 1;
    } else {
      // Last resort: fetch previous season from MLB API.
      try {
        const prev = await mlbApi.get(`/people/${playerId}/stats`, {
          params: { stats: "season", season: season - 1, group },
        });
        const prevSplits = prev.data?.stats?.[0]?.splits || [];
        prevStats = prevSplits[0]?.stat || {};
      } catch { /* expected fallback */ }
    }
  }

  // Return merged: static's rich detail + live current-season stats.
  return {
    ...(staticData || {}),
    detail,
    stats: {
      season,
      group,
      stats: finalStats,
      prevSeason,
      prevStats,
    },
    hasFullData: !!staticData?.detail?.id,
  };
};

export const fetchPlayerSeasonStats = async (playerId, season, group = "hitting") => {
  try {
    const resp = await mlbApi.get(`/people/${playerId}/stats`, {
      params: { stats: "season", season, group },
    });
    return resp.data?.stats?.[0]?.splits?.[0]?.stat || {};
  } catch {
    return {};
  }
};

export const fetchPlayerAdvanced = (playerId) =>
  staticFetch(`players/${playerId}/advanced.json`).catch(() => ({}));

export const fetchMissedCalls = (playerId) =>
  staticFetch(`players/${playerId}/missed_calls.json`).catch(() => null);

export const fetchPlayerArsenal = async (playerId) => {
  // Try static pre-generated data first
  try {
    const data = await staticFetch(`players/${playerId}/arsenal.json`);
    if (data?.pitches?.length) return data;
  } catch { /* expected fallback */ }

  // Fallback: MLB Stats API (works for any pitcher, our team or opponent)
  const year = new Date().getFullYear();
  for (const season of [year, year - 1]) {
    try {
      const resp = await mlbApi.get(`/people/${playerId}/stats`, {
        params: { stats: "pitchArsenal", season, group: "pitching" },
      });
      const splits = resp.data?.stats?.[0]?.splits || [];
      if (splits.length) return formatMlbArsenal(splits);
    } catch { continue; }
  }
  return { pitches: [], totalPitches: 0 };
};

function formatMlbArsenal(splits) {
  const PITCH_NAMES = {
    FF: "4-Seam Fastball", SI: "Sinker", FC: "Cutter", SL: "Slider",
    CU: "Curveball", KC: "Knuckle Curve", CH: "Changeup", FS: "Splitter",
    SV: "Sweeper", ST: "Sweeping Curve", KN: "Knuckleball",
  };
  const pitches = splits.map((s) => {
    const stat = s.stat || {};
    const code = stat.type?.code || s.stat?.pitchType?.code || "";
    return {
      pitchType: code,
      pitchName: PITCH_NAMES[code] || stat.type?.description || code,
      usagePct: stat.percentage != null ? round1(stat.percentage * 100) : null,
      avgVelo: stat.averageSpeed != null ? round1(stat.averageSpeed) : null,
      avgSpin: stat.averageSpin != null ? Math.round(stat.averageSpin) : null,
      whiffRate: stat.swingAndMiss != null ? round1(stat.swingAndMiss * 100) : null,
      baAgainst: stat.battingAverage != null ? stat.battingAverage : null,
      count: stat.totalPitches || 0,
      horzBreak: stat.horizontalBreak != null ? round1(stat.horizontalBreak) : null,
      vertBreak: stat.verticalBreak != null ? round1(stat.verticalBreak) : null,
    };
  }).filter((p) => p.pitchType);
  pitches.sort((a, b) => (b.usagePct || 0) - (a.usagePct || 0));
  return { pitches, totalPitches: pitches.reduce((sum, p) => sum + (p.count || 0), 0) };
}

export const fetchPlayerDominance = (playerId) =>
  Promise.resolve({}); // Not pre-generated yet, can add later

export const fetchSprayChart = (playerId, homeTeam) =>
  staticFetch(`players/${playerId}/spray/${homeTeam}.json`).catch(() => ({ hits: [], summary: {} }));

export const fetchVenues = () => staticFetch("venues.json");

export const fetchPlayoffOdds = () =>
  Promise.resolve({ teams: [] }); // FanGraphs scraping removed, can add to generate script later



// Fetch lineup for a game — returns actual lineup if posted, null if not yet available
export const fetchGameLineup = async (gamePk, teamId) => {
  try {
    const resp = await mlbApi.get(`/game/${gamePk}/boxscore`);
    const teams = resp.data?.teams || {};
    const side = teams.home?.team?.id === teamId ? teams.home : teams.away;
    const order = side?.battingOrder || [];
    if (!order.length) return null;

    const players = side.players || {};
    return order.map((pid, i) => {
      const p = players[`ID${pid}`] || {};
      const person = p.person || {};
      const pos = p.position || {};
      const batting = p.seasonStats?.batting || {};
      return {
        id: pid,
        fullName: person.fullName || "",
        position: pos.abbreviation || "",
        avg: batting.avg || ".000",
        order: i + 1,
      };
    });
  } catch {
    return null;
  }
};

// Projected lineup: use recent game boxscores, fallback to roster-based projection
export const fetchProjectedLineup = async (teamId) => {
  try {
    // Try to build lineup from recent games
    const today = new Date();
    const startDate = new Date(today);
    startDate.setDate(startDate.getDate() - 14);
    const startStr = `${startDate.getFullYear()}-${String(startDate.getMonth()+1).padStart(2,"0")}-${String(startDate.getDate()).padStart(2,"0")}`;
    const endStr = `${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`;

    const schedResp = await mlbApi.get("/schedule", {
      params: { teamId, sportId: 1, startDate: startStr, endDate: endStr, gameType: "R", hydrate: "linescore" },
    });

    const recentGames = [];
    for (const date of schedResp.data?.dates || []) {
      for (const g of date.games || []) {
        if (isTerminalDetailedState(g.status?.detailedState)) {
          recentGames.push(g.gamePk);
        }
      }
    }

    // Get batting orders from recent games (last 5 max)
    const gamePks = recentGames.slice(-5);
    if (gamePks.length > 0) {
      const lineups = await Promise.all(
        gamePks.map(async (gpk) => {
          try {
            const resp = await mlbApi.get(`/game/${gpk}/boxscore`);
            const teams = resp.data?.teams || {};
            const side = teams.home?.team?.id === Number(teamId) ? teams.home : teams.away;
            const order = side?.battingOrder || [];
            if (order.length < 9) return null;
            const players = side?.players || {};
            return order.slice(0, 9).map((id, i) => {
              const p = players[`ID${id}`];
              return {
                id,
                fullName: p?.person?.fullName || "",
                position: p?.position?.abbreviation || "",
                avg: p?.seasonStats?.batting?.avg || ".000",
                order: i + 1,
                projected: true,
              };
            });
          } catch { return null; }
        })
      );

      // Use the most recent valid lineup
      const validLineups = lineups.filter(Boolean);
      if (validLineups.length > 0) {
        return validLineups[validLineups.length - 1];
      }
    }

    // Fallback: position-based projection
    const roster = await fetchRoster(teamId);
    const posPlayers = roster.filter((p) => p.position.type !== "Pitcher");
    const posOrder = ["CF", "SS", "RF", "1B", "DH", "3B", "LF", "2B", "C"];
    const picked = [];
    const used = new Set();
    for (const pos of posOrder) {
      const candidate = posPlayers.find((p) => p.position.abbreviation === pos && !used.has(p.id));
      if (candidate) { picked.push(candidate); used.add(candidate.id); }
    }
    for (const p of posPlayers) {
      if (picked.length >= 9) break;
      if (!used.has(p.id)) { picked.push(p); used.add(p.id); }
    }
    return picked.slice(0, 9).map((p, i) => ({
      id: p.id, fullName: p.fullName, position: p.position.abbreviation,
      avg: ".000", order: i + 1, projected: true,
    }));
  } catch (e) {
    return null;
  }
};

// Fetch live game state: current batter/pitcher, inning, count, outs, linescore, last play
export const fetchLiveGameState = async (gamePk) => {
  try {
    const resp = await axios.get(`https://statsapi.mlb.com/api/v1.1/game/${gamePk}/feed/live`, { timeout: 10000 });
    const ld = resp.data?.liveData || {};
    const ls = ld.linescore || {};
    const plays = ld.plays || {};
    const cp = plays.currentPlay?.matchup || {};
    const teams = ls.teams || {};

    // Find pitcher's game stats from boxscore
    const pitcherId = cp.pitcher?.id;
    let pitcherGameStats = null;
    if (pitcherId) {
      const box = ld.boxscore?.teams || {};
      for (const side of ["away", "home"]) {
        const p = box[side]?.players?.[`ID${pitcherId}`];
        if (p) {
          const ps = p.stats?.pitching || {};
          const seasonPitching = p.seasonStats?.pitching || {};
          pitcherGameStats = {
            ip: ps.inningsPitched || "0",
            pitches: ps.numberOfPitches || 0,
            strikes: ps.strikes || 0,
            k: ps.strikeOuts || 0,
            h: ps.hits || 0,
            er: ps.earnedRuns || 0,
            era: seasonPitching.era || "—",
          };
          break;
        }
      }
    }

    // Find batter's season avg from boxscore
    const batterId = cp.batter?.id;
    let batterAvg = null;
    if (batterId) {
      const box = ld.boxscore?.teams || {};
      for (const side of ["away", "home"]) {
        const p = box[side]?.players?.[`ID${batterId}`];
        if (p) {
          batterAvg = p.seasonStats?.batting?.avg || ".000";
          break;
        }
      }
    }

    // Get game batting line for a player from boxscore
    const getGameBattingLine = (boxscore, playerId) => {
      if (!boxscore || !playerId) return {};
      const box = boxscore.teams || {};
      for (const side of ["away", "home"]) {
        const p = box[side]?.players?.[`ID${playerId}`];
        if (p) {
          const s = p.stats?.batting || {};
          return { ab: s.atBats || 0, h: s.hits || 0, hr: s.homeRuns || 0, rbi: s.rbi || 0, k: s.strikeOuts || 0, bb: s.baseOnBalls || 0, hbp: s.hitByPitch || 0, sb: s.stolenBases || 0 };
        }
      }
      return {};
    };

    // Last completed play
    const allPlays = plays.allPlays || [];
    const completed = allPlays.filter((p) => p.result?.event);
    const lastPlay = completed.length > 0 ? completed[completed.length - 1].result.description : null;

    return {
      inning: ls.currentInning || null,
      inningHalf: ls.inningHalf || "",
      // inningState is more granular than inningHalf — covers Top/Middle/
      // Bottom/End so we can render "Mid 4th" or "End 2nd" between halves.
      // Falls back to inningHalf when MLB doesn't expose the state field.
      inningState: ls.inningState || ls.inningHalf || "",
      outs: ls.outs ?? 0,
      balls: ls.balls ?? 0,
      strikes: ls.strikes ?? 0,
      onFirst: !!ls.offense?.first,
      onSecond: !!ls.offense?.second,
      onThird: !!ls.offense?.third,
      runnerFirst: ls.offense?.first ? { id: ls.offense.first.id, fullName: ls.offense.first.fullName } : null,
      runnerSecond: ls.offense?.second ? { id: ls.offense.second.id, fullName: ls.offense.second.fullName } : null,
      runnerThird: ls.offense?.third ? { id: ls.offense.third.id, fullName: ls.offense.third.fullName } : null,
      batter: cp.batter ? { id: cp.batter.id, fullName: cp.batter.fullName, avg: batterAvg, ...getGameBattingLine(ld.boxscore, cp.batter.id) } : null,
      pitcher: cp.pitcher ? { id: cp.pitcher.id, fullName: cp.pitcher.fullName, gameStats: pitcherGameStats } : null,
      lastPlay,
      lastHitData: (() => {
        // Try completed plays first
        const lastAB = completed.length > 0 ? completed[completed.length - 1] : null;
        const extractRunners = (play) => (play.runners || []).map((r) => ({
          name: r.details?.runner?.fullName || "",
          start: r.movement?.start || null, // null = batter from home
          end: r.movement?.end || null,      // "1B","2B","3B","score", null = out
          isOut: r.movement?.isOut || false,
        }));

        if (lastAB) {
          const hitEvent = (lastAB.playEvents || []).find((e) => e.hitData?.coordinates?.coordX);
          if (hitEvent) {
            const hd = hitEvent.hitData;
            return {
              x: hd.coordinates.coordX,
              y: hd.coordinates.coordY,
              exitVelo: hd.launchSpeed,
              launchAngle: hd.launchAngle,
              distance: hd.totalDistance ? Math.round(hd.totalDistance) : null,
              trajectory: hd.trajectory,
              event: lastAB.result?.event || "",
              description: lastAB.result?.description || "",
              batterName: lastAB.matchup?.batter?.fullName || "",
              runners: extractRunners(lastAB),
            };
          }
        }
        const cp2 = plays.currentPlay;
        if (cp2?.result?.event) {
          const hitEvent = (cp2.playEvents || []).find((e) => e.hitData?.coordinates?.coordX);
          if (hitEvent) {
            const hd = hitEvent.hitData;
            return {
              x: hd.coordinates.coordX,
              y: hd.coordinates.coordY,
              exitVelo: hd.launchSpeed,
              launchAngle: hd.launchAngle,
              distance: hd.totalDistance ? Math.round(hd.totalDistance) : null,
              trajectory: hd.trajectory,
              event: cp2.result.event,
              description: cp2.result.description || "",
              batterName: cp2.matchup?.batter?.fullName || "",
              runners: extractRunners(cp2),
            };
          }
        }
        return null;
      })(),
      currentAtBat: (plays.currentPlay?.playEvents || [])
        .filter((e) => e.details?.description && e.details?.call?.description)
        .map((e) => {
          const d = e.details;
          const speed = e.pitchData?.startSpeed;
          const pitchType = d.type?.description || "";
          const call = d.call?.description || d.description || "";
          const batterName = cp.batter?.fullName || "";
          let action = "";
          if (d.isStrike && d.code === "C") action = `${batterName} takes`;
          else if (d.isStrike && d.code === "S") action = `${batterName} swings and misses`;
          else if (d.isStrike && d.code === "F") action = `${batterName} fouls off`;
          else if (d.isBall) action = `${batterName} takes`;
          else if (d.isInPlay) action = `${batterName} puts in play`;
          else action = batterName;
          const pitchInfo = pitchType ? `${pitchType}${speed ? ` ${speed} mph` : ""}` : "";
          const hd = e.hitData || {};
          const hitData = d.isInPlay && hd.coordinates?.coordX ? {
            x: hd.coordinates.coordX,
            y: hd.coordinates.coordY,
            exitVelo: hd.launchSpeed,
            launchAngle: hd.launchAngle,
            distance: hd.totalDistance ? Math.round(hd.totalDistance) : null,
            trajectory: hd.trajectory,
          } : null;
          const pCoords = e.pitchData?.coordinates;
          const pitch = {
            action, pitchInfo, call, hitData, code: d.code || "",
            pX: pCoords?.pX ?? null,
            pZ: pCoords?.pZ ?? null,
            szTop: e.pitchData?.strikeZoneTop ?? null,
            szBot: e.pitchData?.strikeZoneBottom ?? null,
            isBall: !!d.isBall, isStrike: !!d.isStrike, isInPlay: !!d.isInPlay,
            count: e.count ? `${e.count.balls}-${e.count.strikes}` : null,
          };
          return pitch;
        })
        ,
      currentPlayComplete: !!plays.currentPlay?.result?.event,
      onDeck: ls.offense?.onDeck ? { id: ls.offense.onDeck.id, fullName: ls.offense.onDeck.fullName, ...getGameBattingLine(ld.boxscore, ls.offense.onDeck.id) } : null,
      inHole: ls.offense?.inHole ? { id: ls.offense.inHole.id, fullName: ls.offense.inHole.fullName, ...getGameBattingLine(ld.boxscore, ls.offense.inHole.id) } : null,
      scoringPlays: allPlays
        .filter(didRunScore)
        .map((p) => {
          const hitEv = (p.playEvents || []).find((e) => e.hitData?.coordinates?.coordX);
          const hd = hitEv?.hitData;
          // Extract pre-play runner state from runners array
          const runners = p.runners || [];
          const runnersOn = { first: false, second: false, third: false };
          const runnerNames = {};
          for (const r of runners) {
            const origin = r.movement?.originBase || r.movement?.start;
            const name = r.details?.runner?.fullName || "";
            if (origin === "1B") { runnersOn.first = true; runnerNames.first = name; }
            else if (origin === "2B") { runnersOn.second = true; runnerNames.second = name; }
            else if (origin === "3B") { runnersOn.third = true; runnerNames.third = name; }
          }
          return {
            inning: p.about?.inning || 0,
            halfInning: p.about?.halfInning || "",
            description: scoringDescription(p),
            event: p.result?.event || "",
            awayScore: p.result?.awayScore ?? 0,
            homeScore: p.result?.homeScore ?? 0,
            hrDistance: hd?.totalDistance ? Math.round(hd.totalDistance) : null,
            runnersOn,
            runnerNames,
            hitData: hd ? {
              x: hd.coordinates.coordX,
              y: hd.coordinates.coordY,
              exitVelo: hd.launchSpeed,
              launchAngle: hd.launchAngle,
              distance: hd.totalDistance ? Math.round(hd.totalDistance) : null,
              trajectory: hd.trajectory,
              event: p.result?.event || "",
              description: p.result?.description || "",
              batterName: p.matchup?.batter?.fullName || "",
              runners: runners.map((r) => ({
                name: r.details?.runner?.fullName || "",
                start: r.movement?.start || null,
                end: r.movement?.end || null,
                isOut: r.movement?.isOut || false,
              })),
            } : null,
          };
        }),
      linescore: {
        innings: (ls.innings || []).map((inn) => ({ num: inn.num, away: inn.away?.runs ?? "", home: inn.home?.runs ?? "" })),
        away: { runs: teams.away?.runs ?? 0, hits: teams.away?.hits ?? 0, errors: teams.away?.errors ?? 0 },
        home: { runs: teams.home?.runs ?? 0, hits: teams.home?.hits ?? 0, errors: teams.home?.errors ?? 0 },
      },
    };
  } catch {
    return null;
  }
};

// ---- New data sources ----

/** Season game log (W/L per game, running win%, from pybaseball schedule_and_record) */
export const fetchGameLogs = (teamId) => {
  const abbr = getTeamAbbr(teamId);
  return staticFetch(`teams/${abbr}/gamelogs.json`).catch(() => []);
};

/** Umpire profile from pybaseballstats (accuracy%, zone size, pitcher/batter-friendly) */
export const fetchUmpireProfile = (umpireName) => {
  if (!umpireName) return Promise.resolve(null);
  // Try static pre-generated data first, fall back to live backend
  const slug = umpireName.toLowerCase().replace(/\s+/g, "_");
  return staticFetch(`umpires/${slug}.json`).catch(() =>
    // Live backend call
    axios.get(`/api/umpire/${encodeURIComponent(umpireName)}`).then((r) => r.data).catch(() => null)
  );
};

// PrizePicks hitter scoring table — kept in sync with the backend constant
// in backend/app/services/fantasy.py. Used to compute LIVE fantasy scores
// from in-progress boxscores directly in the browser (no backend needed).
const PP_SCORING = {
  single: 3,
  double: 5,
  triple: 8,
  home_run: 10,
  run: 2,
  rbi: 2,
  walk: 2,
  hbp: 2,
  sb: 5,
};

function _scoreFromBattingStat(s) {
  if (!s) return 0;
  const n = (v) => {
    const x = typeof v === "number" ? v : parseInt(v || 0, 10);
    return Number.isFinite(x) ? x : 0;
  };
  const hits = n(s.hits);
  const doubles = n(s.doubles);
  const triples = n(s.triples);
  const hr = n(s.homeRuns);
  const singles = Math.max(0, hits - doubles - triples - hr);
  return (
    PP_SCORING.single * singles +
    PP_SCORING.double * doubles +
    PP_SCORING.triple * triples +
    PP_SCORING.home_run * hr +
    PP_SCORING.run * n(s.runs) +
    PP_SCORING.rbi * n(s.rbi) +
    PP_SCORING.walk * n(s.baseOnBalls) +
    PP_SCORING.hbp * n(s.hitByPitch) +
    PP_SCORING.sb * n(s.stolenBases)
  );
}

// Live + Final fantasy scores for every batter in an in-progress or already-
// finished game today. Returns
//   { [playerId: number]: { efp: number, gamePk: number, status: string,
//                            state: "live" | "final" } }
// Scheduled games (not yet started) are absent. Live games drive the red
// border + "● LIVE X.X" chip; Final games drive the neutral "FINAL X.X" chip
// so users can see how their pick ended up.
export const fetchLiveFantasyScores = async () => {
  try {
    const d = new Date();
    const dateStr = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
    const schedResp = await mlbApi.get("/schedule", {
      params: { sportId: 1, date: dateStr, gameType: "R" },
    });
    const LIVE_STATES = new Set([
      "In Progress",
      "Manager Challenge",
      "Delayed",
      "Delayed Start",
      "Warmup",
    ]);
    const FINAL_STATES = new Set(["Final", "Game Over", "Completed Early"]);
    const games = [];
    for (const dateEntry of schedResp.data?.dates || []) {
      for (const g of dateEntry.games || []) {
        const status = g.status?.detailedState || "";
        if (LIVE_STATES.has(status)) {
          games.push({ gamePk: g.gamePk, status, state: "live" });
        } else if (FINAL_STATES.has(status)) {
          games.push({ gamePk: g.gamePk, status, state: "final" });
        }
      }
    }
    if (games.length === 0) return {};

    const boxPerGame = await Promise.all(
      games.map(async (g) => {
        try {
          const r = await mlbApi.get(`/game/${g.gamePk}/boxscore`);
          const rows = {};
          for (const side of ["away", "home"]) {
            const players = r.data?.teams?.[side]?.players || {};
            for (const key of Object.keys(players)) {
              if (!key.startsWith("ID")) continue;
              const p = players[key];
              const stat = p?.stats?.batting;
              if (!stat || !stat.plateAppearances) continue;
              const pid = p?.person?.id;
              if (!pid) continue;
              rows[pid] = {
                efp: Number(_scoreFromBattingStat(stat).toFixed(2)),
                gamePk: g.gamePk,
                status: g.status,
                state: g.state,
              };
            }
          }
          return rows;
        } catch {
          return {};
        }
      })
    );
    return Object.assign({}, ...boxPerGame);
  } catch {
    return {};
  }
};

// Today's confirmed lineups keyed by teamId. Returns a plain object
//   { [teamId: number]: number[] }  -- array of starter player IDs per team.
// Teams that haven't posted a lineup yet are absent from the result (so
// the caller can tell "no lineup posted" from "empty lineup"). Hits MLB
// directly — static files don't have live lineup info, and the daily
// GH Action regenerates too infrequently to be useful here.
export const fetchTodayLineups = async () => {
  try {
    const d = new Date();
    const dateStr = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
    const resp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1,
        date: dateStr,
        hydrate: "lineups,team",
        gameType: "R",
      },
    });
    const byTeam = {};
    for (const dateEntry of resp.data?.dates || []) {
      for (const g of dateEntry.games || []) {
        const lineups = g.lineups || {};
        const awayTeamId = g.teams?.away?.team?.id;
        const homeTeamId = g.teams?.home?.team?.id;
        const extract = (side, teamId) => {
          if (!teamId) return;
          const arr = lineups[`${side}Players`] || lineups[side] || [];
          if (!Array.isArray(arr) || arr.length === 0) return;
          const ids = [];
          for (const p of arr) {
            const pid = p?.id || p?.person?.id;
            if (pid) ids.push(Number(pid));
          }
          if (ids.length > 0) byTeam[Number(teamId)] = ids;
        };
        extract("away", awayTeamId);
        extract("home", homeTeamId);
      }
    }
    return byTeam;
  } catch {
    return {};
  }
};

// Fantasy Score projections.
// Prod: a static JSON regenerated twice daily by the refresh-data workflow
// (scripts/generate_fantasy_projections.py writes it into frontend/public/data/fantasy/).
// Dev fallback: hit the local FastAPI endpoint if the static file isn't present.
// Returns { date, season, weights_version, calibrated, metrics, game_count,
//           projection_count, projections: [...], generated_at } or an empty
// shape on total failure.
export const fetchFantasyProjections = async () => {
  try {
    return await staticFetch("fantasy/projections_today.json");
  } catch {
    try {
      const resp = await axios.get("/api/fantasy/projections", { timeout: 60000 });
      return resp.data || { projections: [] };
    } catch {
      return { projections: [], projection_count: 0, game_count: 0 };
    }
  }
};

// Today's locked confidence picks (written once per day by the first
// cron run that sees edge-z badges). Persists through games + final so
// the user can track their morning picks live all day without them
// shuffling or disappearing as the feed updates. Returns null when no
// lock exists yet (e.g. pre-PP-lines-posting morning).
export const fetchTodaysPicksLock = async () => {
  try {
    return await staticFetch("fantasy/todays_picks_lock.json");
  } catch {
    return null;
  }
};

// Today's pre-built parlay ideas (two 2-mans, a 3-man, a 4-man). Same
// lifecycle as todays_picks_lock.json — written by the morning lock run
// off the locked pick set so the "Parlay Ideas" button has stable
// content to show. Returns null when no parlay file exists yet.
export const fetchTodaysParlays = async () => {
  try {
    return await staticFetch("fantasy/todays_parlays.json");
  } catch {
    return null;
  }
};

// New — curated 5-6 parlay slate combining fantasy-edge picks with the
// Edge repo's Model 1 Hits/TB/HR picks. Written by the same morning
// lock as todays_parlays.json (see generate_fantasy_projections.py).
export const fetchTodaysBestParlays = async () => {
  try {
    return await staticFetch("fantasy/todays_best_parlays.json");
  } catch {
    return null;
  }
};

// Reboot watchlist — every Model 1 pick with reboot_rate ≥ 15%, enriched
// with bat/throw platoon matchup + an alignment "hint" (aligned_over,
// aligned_under, split, or unknown). Independent of whether the pick
// made it into a parlay combo — this is the raw reboot × matchup view.
export const fetchTodaysRebootWatch = async () => {
  try {
    return await staticFetch("fantasy/todays_reboot_watch.json");
  } catch {
    return null;
  }
};

// Manual refresh — kick the morning-lock pipeline + Edge-repo Model 1
// generator so today's PP lines / projections / parlays / best-parlays
// all rebuild off the latest data. Only works against a local backend
// (the button in BestParlays degrades gracefully if the POST fails).
export const triggerRefresh = async ({ includeModel = true } = {}) => {
  const { data } = await axios.post("/api/fantasy/refresh", null, {
    params: { include_model: includeModel },
    // Pipeline takes ~60-120s end-to-end; give it plenty of headroom
    // before axios bails. 4 min is generous but avoids false failures
    // on a slow day (PP throttled, big slate).
    timeout: 240_000,
  });
  return data;
};

export const fetchRefreshStatus = async () => {
  try {
    const { data } = await axios.get("/api/fantasy/refresh/status", {
      timeout: 5000,
    });
    return data;
  } catch {
    return { state: "unavailable" };
  }
};

// -----------------------------------------------------------------------
// Remote refresh via GitHub Actions workflow_dispatch.
//
// Works from anywhere the user can reach api.github.com — phone, another
// laptop, the deployed GitHub Pages site. Requires a fine-scoped GitHub
// PAT stored in localStorage (user enters it once). See RefreshButton.
//
// Why we can get away with a client-side PAT:
//   - Repo is public but "Actions: write" scope is the only thing
//     the token needs. No read access to secrets, no code write.
//   - Stored in localStorage, not sent to any third party. It goes
//     directly to api.github.com from the browser.
//   - If the user loses the device, they can revoke the token in 5s
//     at github.com/settings/tokens.
// -----------------------------------------------------------------------

// Hardcoded repo + workflow identity — matches the existing
// refresh-fantasy.yml workflow that already runs on cron.
const GH_REPO_OWNER = "statsleuthgame";
const GH_REPO_NAME  = "baseball-app";
const GH_WORKFLOW   = "refresh-fantasy.yml";
const GH_BRANCH     = "main";

const GH_TOKEN_KEY  = "edge_gh_pat_v1";

export const getStoredGhToken = () => {
  try { return localStorage.getItem(GH_TOKEN_KEY) || null; } catch { return null; }
};
export const setStoredGhToken = (token) => {
  try {
    if (token) localStorage.setItem(GH_TOKEN_KEY, token);
    else       localStorage.removeItem(GH_TOKEN_KEY);
  } catch {
    /* private-mode Safari etc — fall through */
  }
};

/** Fire-and-forget workflow_dispatch. Returns { ok, workflowRunUrl }. */
export const triggerRemoteRefresh = async () => {
  const token = getStoredGhToken();
  if (!token) throw new Error("NO_TOKEN");
  const url = `https://api.github.com/repos/${GH_REPO_OWNER}/${GH_REPO_NAME}`
            + `/actions/workflows/${GH_WORKFLOW}/dispatches`;
  const resp = await axios.post(url, { ref: GH_BRANCH }, {
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
    },
    timeout: 20_000,
  });
  // 204 = accepted (no body). Anything else is unexpected.
  if (resp.status !== 204) {
    throw new Error(`Unexpected GitHub API status ${resp.status}`);
  }
  return {
    ok: true,
    workflowRunUrl: `https://github.com/${GH_REPO_OWNER}/${GH_REPO_NAME}/actions/workflows/${GH_WORKFLOW}`,
  };
};

/** URL the user can open in a new tab to trigger the workflow manually
    (the zero-setup path — no PAT needed, just a GitHub login). */
export const remoteRefreshFallbackUrl = () =>
  `https://github.com/${GH_REPO_OWNER}/${GH_REPO_NAME}/actions/workflows/${GH_WORKFLOW}`;

// Yesterday's graded recap: how many HIGH/MED/LOW/FADE picks, how many
// hit the PP line, standout hits + misses. Written by the nightly
// resolve-pp-lines workflow. Returns null when no recap exists yet
// (first day of the season, pipeline just starting, etc.).
export const fetchYesterdayRecap = async () => {
  try {
    return await staticFetch("fantasy/yesterday_recap.json");
  } catch {
    return null;
  }
};

// Running season totals across all resolved days. Same shape as daily
// recap's `totals` block plus per-day timeline.
export const fetchSeasonRecap = async () => {
  try {
    return await staticFetch("fantasy/season_recap.json");
  } catch {
    return null;
  }
};

// ---- Live data (MLB Stats API, called directly from browser) ----
export const fetchTodayGame = async (teamId) => {
  const today = new Date();
  const endDate = new Date(today);
  endDate.setDate(endDate.getDate() + 14);

  const fmt = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

  try {
    // Check today first
    const todayResp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1, teamId, date: fmt(today),
        hydrate: "team,linescore,probablePitcher,officials,venue(location)", gameType: "R",
      },
    });

    const todayGames = todayResp.data.dates?.[0]?.games || [];

    // Live or scheduled game today
    const liveOrScheduled = todayGames.find((g) =>
      ["In Progress", "Scheduled", "Pre-Game", "Warmup", "Delayed Start", "Delayed", "Suspended"].includes(g.status?.detailedState)
    );
    if (liveOrScheduled) return formatGame(liveOrScheduled, true);

    // Final game today - also find next game (covers Final, Game Over,
    // Completed Early, Final: Tied — all terminal MLB statuses).
    const finalGame = todayGames.find((g) => isTerminalDetailedState(g.status?.detailedState));

    // Get upcoming games
    const futureResp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1, teamId, startDate: fmt(today), endDate: fmt(endDate),
        hydrate: "team,linescore,probablePitcher,officials,venue(location)", gameType: "R",
      },
    });

    const allDates = futureResp.data.dates || [];
    let nextGame = null;
    for (const dateEntry of allDates) {
      const gameDate = new Date(dateEntry.date + "T00:00:00");
      if (gameDate <= today) continue;
      if (dateEntry.games?.length) {
        nextGame = dateEntry.games[0];
        break;
      }
    }

    if (finalGame) {
      const result = formatGame(finalGame, false);
      result.nextGame = nextGame ? formatGame(nextGame, true) : null;
      return result;
    }

    if (nextGame) return formatGame(nextGame, true);
    return { noGame: true, message: "No games scheduled in the next 14 days." };
  } catch (e) {
    /* game fetch failed */
    return { noGame: true, message: "Unable to load game data." };
  }
};

// Fetch hot/cold players for a team (last 7 games)
export const fetchHotColdPlayers = async (teamId) => {
  try {
    const roster = await fetchRoster(teamId);
    const batters = roster.filter((p) => p.position.type !== "Pitcher");
    const results = await Promise.all(
      batters.map(async (p) => {
        try {
          const resp = await mlbApi.get(`/people/${p.id}/stats`, {
            params: { stats: "lastXGames", group: "hitting", gameType: "R", limit: 7 },
          });
          let s = resp.data?.stats?.[0]?.splits?.[0]?.stat || {};
          let ab = s.atBats || 0;
          // Early season fallback: include spring training if not enough regular season data
          if (ab < 3) {
            const stResp = await mlbApi.get(`/people/${p.id}/stats`, {
              params: { stats: "lastXGames", group: "hitting", gameType: "S", limit: 7 },
            });
            const st = stResp.data?.stats?.[0]?.splits?.[0]?.stat || {};
            if ((st.atBats || 0) > ab) { s = st; ab = st.atBats || 0; }
          }
          if (ab < 3) return null;
          return {
            id: p.id,
            fullName: p.fullName,
            position: p.position.abbreviation,
            avg: s.avg || ".000",
            ops: s.ops || ".000",
            hits: s.hits || 0,
            hr: s.homeRuns || 0,
            ab,
          };
        } catch { return null; }
      })
    );
    const valid = results.filter(Boolean);
    const hot = [...valid].sort((a, b) => parseFloat(b.ops) - parseFloat(a.ops)).slice(0, 3);
    const cold = [...valid].sort((a, b) => parseFloat(a.ops) - parseFloat(b.ops)).slice(0, 3);
    return { hot, cold };
  } catch {
    return { hot: [], cold: [] };
  }
};

// Fetch bullpen availability for a team (excludes starters)
export const fetchBullpenAvailability = async (teamId, starterIds = []) => {
  try {
    const roster = await fetchRoster(teamId);
    const pitchers = roster.filter((p) => p.position.type === "Pitcher" && !starterIds.includes(p.id));
    const season = new Date().getFullYear();
    const today = new Date();

    const results = await Promise.all(
      pitchers.map(async (p) => {
        try {
          // Fetch current + prior season stats and game log
          const [curResp, prevResp, logResp] = await Promise.all([
            mlbApi.get(`/people/${p.id}/stats`, { params: { stats: "season", group: "pitching", season } }),
            mlbApi.get(`/people/${p.id}/stats`, { params: { stats: "season", group: "pitching", season: season - 1 } }),
            mlbApi.get(`/people/${p.id}/stats`, { params: { stats: "gameLog", group: "pitching", gameType: "R", season, limit: 3 } }),
          ]);

          // Skip starters (GS > 50% of games) — check current season first, fall back to prior
          const curStat = curResp.data?.stats?.[0]?.splits?.[0]?.stat || {};
          const prevStat = prevResp.data?.stats?.[0]?.splits?.[0]?.stat || {};
          const stat = (curStat.gamesPlayed || 0) > 0 ? curStat : prevStat;
          const gp = stat.gamesPlayed || 0;
          const gs = stat.gamesStarted || 0;
          if (gp > 0 && gs / gp > 0.5) return null;

          // Game log returns chronological (oldest first) — most recent is last
          const splits = logResp.data?.stats?.[0]?.splits || [];
          let lastGameDate = null;
          let daysRest = 99;
          let recentPitches = 0;
          let recentGames = 0;

          for (const s of splits) {
            const gDate = new Date(s.date);
            const daysDiff = Math.floor((today - gDate) / (1000 * 60 * 60 * 24));
            // Always update — last iteration wins (most recent game)
            lastGameDate = s.date;
            daysRest = daysDiff;
            if (daysDiff <= 3) {
              recentPitches += s.stat?.numberOfPitches || 0;
              recentGames++;
            }
          }

          let status = "available";
          if (daysRest === 0) status = "unavailable";
          else if (daysRest === 1 && recentPitches > 25) status = "limited";
          else if (recentGames >= 3 && daysRest <= 1) status = "unavailable";

          return {
            id: p.id,
            fullName: p.fullName,
            daysRest,
            recentPitches,
            status,
            lastGameDate,
          };
        } catch {
          return null;
        }
      })
    );

    return results.filter(Boolean).sort((a, b) => a.daysRest - b.daysRest);
  } catch {
    return [];
  }
};

// Fetch injured list for a team (40-man roster IL players)
export const fetchTeamInjuries = async (teamId) => {
  try {
    const season = new Date().getFullYear();
    const resp = await mlbApi.get(`/teams/${teamId}/roster`, {
      params: { rosterType: "40Man", season },
    });
    return (resp.data?.roster || [])
      .filter((r) => r.status?.description?.toLowerCase().includes("injured"))
      .map((r) => ({
        id: r.person?.id,
        fullName: r.person?.fullName || "",
        position: r.position?.abbreviation || "",
        ilType: r.status?.description || "",
      }));
  } catch {
    return [];
  }
};

export const fetchBvP = async (batterId, pitcherId) => {
  try {
    const bvp = await staticFetch(`players/${batterId}/bvp.json`);
    return bvp[String(pitcherId)] || { pa: 0 };
  } catch {
    return { pa: 0 };
  }
};



export const fetchParkHistory = async (teamId) => {
  try {
    const abbr = getTeamAbbr(teamId);
    const schedule = await staticFetch(`teams/${abbr}/schedule.json`);
    const finals = schedule.filter((g) => g.status === "Final");
    if (!finals.length) return null; // Season hasn't started
    const wins = finals.filter((g) => {
      const isHome = Number(g.home.id) === Number(teamId);
      return isHome ? g.home.isWinner : g.away.isWinner;
    }).length;
    const losses = finals.length - wins;
    return { wins, losses, winPct: finals.length > 0 ? round3(wins / finals.length) : null, recentGames: [] };
  } catch {
    return null;
  }
};

export const fetchPriorMatchups = async (team1, team2) => {
  try {
    // Fetch live from MLB API so the series is always current (static data can be stale)
    const season = new Date().getFullYear();
    const startDate = `${season}-03-01`;
    const endDate = `${season}-11-30`;
    const resp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1,
        teamId: team1,
        opponentId: team2,
        startDate,
        endDate,
        gameType: "R",
      },
    });

    const games = [];
    for (const date of resp.data?.dates || []) {
      for (const g of date.games || []) games.push(g);
    }
    if (!games.length) return null;

    const played = games.filter((g) => isTerminalDetailedState(g.status?.detailedState));
    const upcoming = games.filter((g) => !isTerminalDetailedState(g.status?.detailedState));

    const computeWon = (g) => {
      const isHome = Number(g.teams?.home?.team?.id) === Number(team1);
      const homeScore = g.teams?.home?.score ?? 0;
      const awayScore = g.teams?.away?.score ?? 0;
      return isHome ? homeScore > awayScore : awayScore > homeScore;
    };

    const wins = played.filter(computeWon).length;

    const mapGame = (g) => ({
      gamePk: g.gamePk,
      date: g.gameDate,
      homeAbbr: g.teams?.home?.team?.abbreviation || getTeamAbbr(g.teams?.home?.team?.id),
      awayAbbr: g.teams?.away?.team?.abbreviation || getTeamAbbr(g.teams?.away?.team?.id),
      homeScore: g.teams?.home?.score,
      awayScore: g.teams?.away?.score,
      won: computeWon(g),
    });

    return {
      played: played.map(mapGame),
      upcoming: upcoming.map(mapGame),
      record: { wins, losses: played.length - wins },
    };
  } catch {
    return { played: [], upcoming: [], record: { wins: 0, losses: 0 } };
  }
};

// ---- New Features: Live MLB API calls ----

// Pregame moneyline odds (consensus median across US books) for the given
// local-ET date. Calls a Cloudflare Worker that holds the The Odds API key.
// When VITE_ODDS_PROXY_URL is unset, returns null so the scoreboard can hide
// the Refresh button gracefully.
const ODDS_PROXY_URL = (import.meta.env.VITE_ODDS_PROXY_URL || "").replace(/\/+$/, "");
export const ODDS_PROXY_CONFIGURED = !!ODDS_PROXY_URL;

export const fetchOddsForDate = async (dateStr) => {
  if (!ODDS_PROXY_URL) return null;
  const resp = await axios.get(`${ODDS_PROXY_URL}/odds`, {
    params: { date: dateStr },
    timeout: 12000,
  });
  const byMatchup = new Map();
  for (const g of resp.data?.games || []) {
    if (!g?.away_team || !g?.home_team) continue;
    byMatchup.set(`${g.away_team}@${g.home_team}`, g);
  }
  return {
    updatedAt: resp.data?.updated_at || null,
    remaining: resp.data?.remaining ?? null,
    byMatchup,
  };
};

// All MLB games today (scoreboard)
export const fetchAllGamesToday = async (dateStr) => {
  try {
    const dateParam = dateStr || (() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; })();
    const resp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1, date: dateParam,
        hydrate: "team,linescore,probablePitcher,weather,venue(location),decisions", gameType: "R",
      },
    });
    const games = [];
    for (const dateEntry of resp.data?.dates || []) {
      for (const g of dateEntry.games || []) {
        const away = g.teams?.away || {};
        const home = g.teams?.home || {};
        const at = away.team || {};
        const ht = home.team || {};
        const ls = g.linescore || {};
        const w = g.weather || {};
        // Extract inning-by-inning linescore
        const innings = (ls.innings || []).map((inn) => ({
          num: inn.num,
          away: inn.away?.runs ?? "",
          home: inn.home?.runs ?? "",
        }));
        const lsTeams = ls.teams || {};
        const linescore = innings.length ? {
          innings,
          away: { runs: lsTeams.away?.runs ?? 0, hits: lsTeams.away?.hits ?? 0, errors: lsTeams.away?.errors ?? 0 },
          home: { runs: lsTeams.home?.runs ?? 0, hits: lsTeams.home?.hits ?? 0, errors: lsTeams.home?.errors ?? 0 },
        } : null;

        games.push({
          gamePk: g.gamePk,
          gameDate: g.gameDate || "",
          status: normalizeStatus(g.status?.detailedState),
          inning: ls.currentInning || null,
          inningHalf: ls.inningHalf || "",
          venue: g.venue?.name || "",
          venueLocation: g.venue?.location ? `${g.venue.location.city}, ${g.venue.location.stateAbbrev}` : "",
          weather: w.temp ? { temp: w.temp, condition: w.condition || "", wind: w.wind || "" } : null,
          linescore,
          away: {
            id: at.id, name: at.name || "", abbreviation: at.abbreviation || "",
            score: away.score, wins: away.leagueRecord?.wins, losses: away.leagueRecord?.losses,
            probablePitcher: extractPitcher(away.probablePitcher),
            logoUrl: `https://www.mlbstatic.com/team-logos/team-cap-on-dark/${at.id}.svg`,
          },
          home: {
            id: ht.id, name: ht.name || "", abbreviation: ht.abbreviation || "",
            score: home.score, wins: home.leagueRecord?.wins, losses: home.leagueRecord?.losses,
            probablePitcher: extractPitcher(home.probablePitcher),
            logoUrl: `https://www.mlbstatic.com/team-logos/team-cap-on-dark/${ht.id}.svg`,
          },
          decisions: g.decisions ? {
            winner: g.decisions.winner ? { id: g.decisions.winner.id, name: g.decisions.winner.fullName } : null,
            loser: g.decisions.loser ? { id: g.decisions.loser.id, name: g.decisions.loser.fullName } : null,
            save: g.decisions.save ? { id: g.decisions.save.id, name: g.decisions.save.fullName } : null,
          } : null,
        });
      }
    }
    return games;
  } catch {
    return [];
  }
};

// Box score + at-bat details for expanded game view
function formatAtBatShort(event, desc, hrDistance) {
  const d = desc.toLowerCase();
  const dir = d.match(/to (left|right|center|left-center|right-center)\s*(field)?/)?.[1] || "";
  const dirStr = dir ? ` to ${dir} field` : "";

  switch (event) {
    case "Strikeout":
      return d.includes("looking") || d.includes("called") ? "Strikeout looking" : "Strikeout swinging";
    case "Single": return `Single${dirStr}`;
    case "Double": return `Double${dirStr}`;
    case "Triple": return `Triple${dirStr}`;
    case "Home Run": return `Home run${dirStr}${hrDistance ? ` (${hrDistance} ft)` : ""}`;
    case "Walk": return "Walk";
    case "Intent Walk": return "Intentional walk";
    case "Hit By Pitch": return "Hit by pitch";
    case "Flyout": return `Flyout${dirStr}`;
    case "Lineout": return `Lineout${dirStr}`;
    case "Pop Out": return `Pop out${dirStr}`;
    case "Groundout": return `Groundout${d.includes("shortstop") ? " to short" : d.includes("second") ? " to second" : d.includes("third") ? " to third" : d.includes("first") ? " to first" : d.includes("pitcher") ? " to pitcher" : ""}`;
    case "Grounded Into DP": return "Grounded into double play";
    case "Fielders Choice": return "Fielder's choice";
    case "Sac Fly": return `Sac fly${dirStr}`;
    case "Sac Bunt": return "Sac bunt";
    case "Force Out": return "Force out";
    case "Field Error": return "Reached on error";
    default: return event || "Unknown";
  }
}

export const fetchGameDetail = async (gamePk) => {
  try {
    const [boxResp, pbpResp] = await Promise.all([
      mlbApi.get(`/game/${gamePk}/boxscore`),
      mlbApi.get(`/game/${gamePk}/playByPlay`),
    ]);

    const allPlays = pbpResp.data?.allPlays || [];

    // Build at-bats grouped by batter ID
    const atBatsByBatter = {};
    for (const play of allPlays) {
      const batterId = play.matchup?.batter?.id;
      if (!batterId || !play.result?.event) continue;
      if (!atBatsByBatter[batterId]) atBatsByBatter[batterId] = [];
      let hrDistance = null;
      if (play.result.event === "Home Run") {
        const hitEvent = (play.playEvents || []).find((e) => e.hitData?.totalDistance);
        if (hitEvent) hrDistance = Math.round(hitEvent.hitData.totalDistance);
      }
      atBatsByBatter[batterId].push({
        inning: play.about?.inning || 0,
        halfInning: play.about?.halfInning || "",
        event: play.result.event,
        description: play.result.description || "",
        shortDesc: formatAtBatShort(play.result.event, play.result.description || "", hrDistance),
        rbi: play.result.rbi ?? 0,
        isScoring: didRunScore(play),
        hrDistance,
      });
    }

    // Extract scoring plays
    const scoringPlays = allPlays
      .filter(didRunScore)
      .map((p) => {
        let hrDistance = null;
        const event = p.result?.event || "";
        if (event === "Home Run") {
          const hitEvent = (p.playEvents || []).find((e) => e.hitData?.totalDistance);
          if (hitEvent) hrDistance = Math.round(hitEvent.hitData.totalDistance);
        }
        return {
          inning: p.about?.inning || 0,
          halfInning: p.about?.halfInning || "",
          description: scoringDescription(p),
          awayScore: p.result?.awayScore ?? 0,
          homeScore: p.result?.homeScore ?? 0,
          rbi: p.result?.rbi ?? 0,
          event,
          hrDistance,
        };
      });

    // Parse box score for both teams
    const parseTeam = (teamData) => {
      const batters = (teamData?.batters || []).map((id) => {
        const p = teamData.players?.[`ID${id}`];
        if (!p) return null;
        const s = p.stats?.batting || {};
        const isP = p.position?.abbreviation === "P";
        // Skip pitchers with no at-bats
        if (isP && !s.atBats) return null;
        return {
          id,
          name: p.person?.fullName || "",
          position: p.position?.abbreviation || "",
          battingOrder: p.battingOrder || "",
          stats: {
            ab: s.atBats ?? 0, r: s.runs ?? 0, h: s.hits ?? 0,
            rbi: s.rbi ?? 0, bb: s.baseOnBalls ?? 0, k: s.strikeOuts ?? 0,
            hr: s.homeRuns ?? 0, sb: s.stolenBases ?? 0, avg: s.avg || "",
          },
          atBats: atBatsByBatter[id] || [],
        };
      }).filter(Boolean);

      const pitchers = (teamData?.pitchers || []).map((id) => {
        const p = teamData.players?.[`ID${id}`];
        if (!p) return null;
        const s = p.stats?.pitching || {};
        return {
          id,
          name: p.person?.fullName || "",
          stats: {
            ip: s.inningsPitched ?? "0",
            h: s.hits ?? 0,
            r: s.runs ?? 0,
            er: s.earnedRuns ?? 0,
            bb: s.baseOnBalls ?? 0,
            k: s.strikeOuts ?? 0,
            pitches: s.numberOfPitches ?? 0,
            strikes: s.strikes ?? 0,
          },
          note: s.note || "",
        };
      }).filter(Boolean);

      return { batters, pitchers };
    };

    const box = boxResp.data?.teams || {};
    const away = parseTeam(box.away);
    const home = parseTeam(box.home);
    return {
      away: away.batters,
      home: home.batters,
      awayPitchers: away.pitchers,
      homePitchers: home.pitchers,
      scoringPlays,
    };
  } catch {
    return null;
  }
};



// Pitcher season stats (ERA, W-L) for scoreboard cards
export const fetchPitcherSeasonStats = async (pitcherId) => {
  const year = new Date().getFullYear();
  for (const season of [year, year - 1]) {
    try {
      const resp = await mlbApi.get(`/people/${pitcherId}/stats`, {
        params: { stats: "season", season, group: "pitching" },
      });
      const stat = resp.data?.stats?.[0]?.splits?.[0]?.stat;
      if (stat && (stat.gamesStarted > 0 || stat.gamesPitched > 0)) {
        return {
          era: stat.era || "-.--",
          wins: stat.wins || 0,
          losses: stat.losses || 0,
          saves: stat.saves || 0,
          ip: stat.inningsPitched || "0",
          so: stat.strikeOuts || 0,
          season,
        };
      }
    } catch { continue; }
  }
  return null;
};

// 3. Transaction feed (roster moves, IL, trades)
export const fetchTransactions = async (teamId) => {
  try {
    const end = new Date();
    const start = new Date();
    start.setDate(start.getDate() - 30);
    const fmt = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
    const resp = await mlbApi.get("/transactions", {
      params: { teamId, startDate: fmt(start), endDate: fmt(end) },
    });
    const mapped = (resp.data?.transactions || []).map((t) => ({
      id: t.id,
      date: t.date,
      type: t.typeCode,
      typeDesc: t.typeDesc,
      description: t.description,
      player: t.person ? { id: t.person.id, name: t.person.fullName } : null,
    }));
    // MLB API returns oldest-first; sort descending so newest appears first
    // and slice AFTER sorting so we keep the 10 most recent (not the 10 oldest).
    mapped.sort((a, b) => new Date(b.date) - new Date(a.date));
    return mapped.slice(0, 10);
  } catch {
    return [];
  }
};

// 4. Player game log (last 10 games)
export const fetchPlayerGameLog = async (playerId, group = "hitting") => {
  const year = new Date().getFullYear();
  for (const season of [year, year - 1]) {
    try {
      const resp = await mlbApi.get(`/people/${playerId}/stats`, {
        params: { stats: "gameLog", season, group },
      });
      const splits = resp.data?.stats?.[0]?.splits || [];
      if (splits.length) {
        return splits.slice(-10).reverse().map((s) => ({
          date: s.date,
          opponent: s.opponent?.abbreviation || s.opponent?.name?.split(" ").pop() || "",
          isHome: s.isHome,
          isWin: s.isWin,
          stat: s.stat,
        }));
      }
    } catch { continue; }
  }
  return [];
};

// Shared aggregator for vs-team splits returned by any MLB stats endpoint.
// AB-weights OBP and SLG so OPS survives multi-season merges.
function aggregateVsTeamSplits(splits) {
  let ab = 0, hits = 0, hr = 0, pa = 0, games = 0;
  let obpSum = 0, slgSum = 0;
  for (const sp of splits || []) {
    const s = sp.stat || {};
    const abSp = s.atBats || 0;
    if (abSp <= 0) continue;
    ab += abSp;
    hits += s.hits || 0;
    hr += s.homeRuns || 0;
    pa += s.plateAppearances || 0;
    games += s.gamesPlayed || 0;
    obpSum += (parseFloat(s.obp) || 0) * abSp;
    slgSum += (parseFloat(s.slg) || 0) * abSp;
  }
  if (ab <= 0) return null;
  return {
    games,
    ab,
    hits,
    hr,
    avg: hits / ab,
    ops: obpSum / ab + slgSum / ab,
    pa,
  };
}

const EMPTY_VS_TEAM = { games: 0, ab: 0, hits: 0, hr: 0, avg: null, ops: null, pa: 0 };

// Current-season batter-vs-team totals.
export const fetchPlayerSeasonVsTeam = async (playerId, opposingTeamId, group = "hitting") => {
  if (!playerId || !opposingTeamId) return EMPTY_VS_TEAM;
  const year = new Date().getFullYear();
  try {
    const resp = await mlbApi.get(`/people/${playerId}/stats`, {
      params: { stats: "vsTeam", group, opposingTeamId, season: year, sportId: 1 },
    });
    const agg = aggregateVsTeamSplits(resp.data?.stats?.[0]?.splits);
    if (agg) return agg;
  } catch {}
  return EMPTY_VS_TEAM;
};

// Career / all-time batter-vs-team totals. Tries native career stat types
// first, then falls back to aggregating year-by-year vsTeam splits. Several
// endpoints on MLB's public stats API silently return a single current-season
// row for `vsTeam` without a season param, so we only trust it as a last
// resort after asking for season-less data with explicit totals.
export const fetchPlayerCareerVsTeam = async (playerId, opposingTeamId, group = "hitting") => {
  if (!playerId || !opposingTeamId) return EMPTY_VS_TEAM;

  // 1. Explicit career stat types that aggregate all years server-side.
  for (const statsType of ["vsTeamTotal", "vsTeam5Y"]) {
    try {
      const resp = await mlbApi.get(`/people/${playerId}/stats`, {
        params: { stats: statsType, group, opposingTeamId, sportId: 1 },
      });
      const agg = aggregateVsTeamSplits(resp.data?.stats?.[0]?.splits);
      // vsTeamTotal must return career; accept if any AB.
      // vsTeam5Y accepted as well (5-year is a close-enough career proxy for
      // nearly every active MLB player).
      if (agg) return agg;
    } catch {}
  }

  // 2. Sum per-season splits via yearByYear with the opposing team filter.
  try {
    const resp = await mlbApi.get(`/people/${playerId}/stats`, {
      params: { stats: "yearByYear", group, opposingTeamId, sportId: 1 },
    });
    const agg = aggregateVsTeamSplits(resp.data?.stats?.[0]?.splits);
    if (agg) return agg;
  } catch {}

  // 3. Last resort: stats=vsTeam without a season param. On this API this
  //    often returns just the current season, so we only use it if nothing
  //    above worked.
  try {
    const resp = await mlbApi.get(`/people/${playerId}/stats`, {
      params: { stats: "vsTeam", group, opposingTeamId, sportId: 1 },
    });
    const agg = aggregateVsTeamSplits(resp.data?.stats?.[0]?.splits);
    if (agg) return agg;
  } catch {}

  return EMPTY_VS_TEAM;
};

// Back-compat alias — older callers expecting a single vs-team function.
export const fetchPlayerVsTeam = fetchPlayerCareerVsTeam;

// 5. Win probability for a game
export const fetchWinProbability = async (gamePk) => {
  try {
    const resp = await mlbApi.get(`/game/${gamePk}/winProbability`);
    return (resp.data || []).map((wp) => ({
      atBatIndex: wp.atBatIndex,
      inning: wp.about?.inning || 0,
      halfInning: wp.about?.halfInning || "top",
      homeProb: (wp.homeTeamWinProbability || 0) / 100,
      awayProb: (wp.awayTeamWinProbability || 0) / 100,
      probAdded: (wp.homeTeamWinProbabilityAdded || 0) / 100,
      leverage: wp.leverageIndex,
    }));
  } catch {
    return [];
  }
};

// 8. Team hot/cold players (our team, last 7 days game logs)
export const fetchTeamHotCold = async (teamId) => {
  try {
    const abbr = getTeamAbbr(teamId);
    const roster = await staticFetch(`teams/${abbr}/roster.json`);
    const batters = roster.filter((p) => p.position.type !== "Pitcher");
    const year = new Date().getFullYear();
    const results = [];

    for (const batter of batters.slice(0, 15)) {
      try {
        const resp = await mlbApi.get(`/people/${batter.id}/stats`, {
          params: { stats: "gameLog", season: year, group: "hitting" },
        });
        const splits = resp.data?.stats?.[0]?.splits || [];
        const last7 = splits.slice(-7);
        if (last7.length < 3) continue;

        let ab = 0, hits = 0, hr = 0, rbi = 0, bb = 0, hbp = 0, sf = 0, doubles = 0, triples = 0;
        for (const g of last7) {
          const s = g.stat;
          ab += s.atBats || 0;
          hits += s.hits || 0;
          hr += s.homeRuns || 0;
          rbi += s.rbi || 0;
          bb += s.baseOnBalls || 0;
          hbp += s.hitByPitch || 0;
          sf += s.sacFlies || 0;
          doubles += s.doubles || 0;
          triples += s.triples || 0;
        }
        if (ab < 10) continue;
        const avg = hits / ab;
        const pa = ab + bb + hbp + sf;
        const obp = pa > 0 ? (hits + bb + hbp) / pa : 0;
        const singles = hits - doubles - triples - hr;
        const tb = singles + doubles * 2 + triples * 3 + hr * 4;
        const slg = ab > 0 ? tb / ab : 0;
        const ops = Math.round((obp + slg) * 1000) / 1000;

        results.push({
          id: batter.id,
          name: batter.fullName,
          position: batter.position.abbreviation,
          games: last7.length, ab, hits, hr, rbi, ops,
          avg: Math.round(avg * 1000) / 1000,
          photoUrl: batter.photoUrl,
          isHot: avg >= .300,
          isCold: avg < .150,
        });
      } catch { continue; }
    }

    results.sort((a, b) => b.avg - a.avg);
    return {
      hot: results.filter((r) => r.isHot).slice(0, 5),
      cold: results.filter((r) => r.isCold).slice(0, 3),
    };
  } catch {
    return { hot: [], cold: [] };
  }
};

// 9. League leaders
export const fetchLeagueLeaders = async () => {
  try {
    const year = new Date().getFullYear();
    const hittingCats = ["homeRuns", "battingAverage", "runsBattedIn", "onBasePlusSlugging", "stolenBases", "hits"];
    const pitchingCats = ["earnedRunAverage", "strikeouts", "wins", "saves", "whip"];
    const hitting = {};
    const pitching = {};

    const fetchCat = async (cat, group, dest) => {
      try {
        const resp = await mlbApi.get("/stats/leaders", {
          params: { leaderCategories: cat, season: year, sportId: 1, limit: 5, statGroup: group },
        });
        const leaders = resp.data?.leagueLeaders?.[0]?.leaders || [];
        dest[cat] = leaders.map((l) => ({
          rank: l.rank,
          value: l.value,
          player: { id: l.person?.id, name: l.person?.fullName },
          team: l.team?.abbreviation || "",
          teamId: l.team?.id,
        }));
      } catch { dest[cat] = []; }
    };

    const longestHrPromise = axios.get("/api/leaderboards/longest-hr", { params: { season: year, limit: 5 }, timeout: 30000 })
      .then((r) => r.data)
      .catch(() => []);

    const [longestHrs] = await Promise.all([
      longestHrPromise,
      ...hittingCats.map((cat) => fetchCat(cat, "hitting", hitting)),
      ...pitchingCats.map((cat) => fetchCat(cat, "pitching", pitching)),
    ]);
    if (longestHrs.length) hitting.longestHomeRun = longestHrs;
    return { hitting, pitching };
  } catch {
    return { hitting: {}, pitching: {} };
  }
};

// 10. Upcoming series (next 4 games with probable pitchers)
export const fetchUpcomingSeries = async (teamId) => {
  try {
    const today = new Date();
    const end = new Date();
    end.setDate(end.getDate() + 10);
    const fmt = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

    const resp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1, teamId,
        startDate: fmt(today), endDate: fmt(end),
        hydrate: "team,probablePitcher", gameType: "R",
      },
    });

    const games = [];
    for (const dateEntry of resp.data?.dates || []) {
      for (const g of dateEntry.games || []) {
        const status = g.status?.detailedState || "";
        if (["Final", "In Progress", "Warmup", "Delayed Start", "Delayed", "Suspended", "Game Over"].includes(status)) continue;
        const away = g.teams?.away || {};
        const home = g.teams?.home || {};
        games.push({
          gamePk: g.gamePk,
          gameDate: g.gameDate,
          venue: g.venue?.name || "",
          away: {
            id: away.team?.id, abbreviation: away.team?.abbreviation || "",
            probablePitcher: extractPitcher(away.probablePitcher),
            logoUrl: `https://www.mlbstatic.com/team-logos/team-cap-on-dark/${away.team?.id}.svg`,
          },
          home: {
            id: home.team?.id, abbreviation: home.team?.abbreviation || "",
            probablePitcher: extractPitcher(home.probablePitcher),
            logoUrl: `https://www.mlbstatic.com/team-logos/team-cap-on-dark/${home.team?.id}.svg`,
          },
        });
        if (games.length >= 4) break;
      }
      if (games.length >= 4) break;
    }
    return games;
  } catch {
    return [];
  }
};

// ---- Helpers ----
function formatGame(g, isNext) {
  const away = g.teams?.away || {};
  const home = g.teams?.home || {};
  const at = away.team || {};
  const ht = home.team || {};

  // Extract home plate umpire from officials list
  const officials = g.officials || [];
  const hpUmpire = officials.find((o) =>
    o.officialType === "Home Plate" || o.officialType === "HP"
  );
  const umpireName = hpUmpire?.official?.fullName || null;

  return {
    gamePk: g.gamePk,
    gameDate: g.gameDate || "",
    status: normalizeStatus(g.status?.detailedState),
    isNextGame: isNext,
    venue: { id: g.venue?.id, name: g.venue?.name || "" },
    venueLocation: g.venue?.location ? `${g.venue.location.city}, ${g.venue.location.stateAbbrev}` : "",
    umpireName,
    away: {
      id: at.id, name: at.name || "", abbreviation: at.abbreviation || "",
      score: away.score,
      wins: away.leagueRecord?.wins, losses: away.leagueRecord?.losses,
      probablePitcher: extractPitcher(away.probablePitcher),
      logoUrl: `https://www.mlbstatic.com/team-logos/team-cap-on-dark/${at.id}.svg`,
    },
    home: {
      id: ht.id, name: ht.name || "", abbreviation: ht.abbreviation || "",
      score: home.score,
      wins: home.leagueRecord?.wins, losses: home.leagueRecord?.losses,
      probablePitcher: extractPitcher(home.probablePitcher),
      logoUrl: `https://www.mlbstatic.com/team-logos/team-cap-on-dark/${ht.id}.svg`,
    },
  };
}

function extractPitcher(p) {
  if (!p) return null;
  return {
    id: p.id,
    fullName: p.fullName || "",
    photoUrl: `https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/${p.id}/headshot/67/current`,
  };
}
