import axios from "axios";

// Static data files generated by GitHub Actions (served from same origin)
const BASE = import.meta.env.BASE_URL || "/";
const dataUrl = (path) => `${BASE}data/${path}`;

const staticFetch = (path) => axios.get(dataUrl(path)).then((r) => r.data);

// MLB Stats API called directly from browser (no backend needed, free & fast)
const mlbApi = axios.create({
  baseURL: "https://statsapi.mlb.com/api/v1",
  timeout: 15000,
});

// ---- Static data (generated daily) ----
export const fetchRoster = (teamId) => {
  const abbr = teamId == 136 ? "SEA" : "ATL";
  return staticFetch(`teams/${abbr}/roster.json`);
};

export const fetchSchedule = (teamId) => {
  const abbr = teamId == 136 ? "SEA" : "ATL";
  return staticFetch(`teams/${abbr}/schedule.json`);
};

export const fetchStandings = () => staticFetch("standings.json");

export const fetchPlayerDetail = (playerId) =>
  staticFetch(`players/${playerId}/info.json`).then((d) => d.detail);

export const fetchPlayerStats = (playerId) =>
  staticFetch(`players/${playerId}/info.json`);

export const fetchPlayerAdvanced = (playerId) =>
  staticFetch(`players/${playerId}/advanced.json`).catch(() => ({}));

export const fetchPlayerArsenal = (playerId) =>
  staticFetch(`players/${playerId}/arsenal.json`).catch(() => ({ pitches: [], totalPitches: 0 }));

export const fetchPlayerDominance = (playerId) =>
  Promise.resolve({}); // Not pre-generated yet, can add later

export const fetchSprayChart = (playerId, homeTeam) =>
  staticFetch(`players/${playerId}/spray/${homeTeam}.json`).catch(() => ({ hits: [], summary: {} }));

export const fetchVenues = () => staticFetch("venues.json");

export const fetchPlayoffOdds = () =>
  Promise.resolve({ teams: [] }); // FanGraphs scraping removed, can add to generate script later

export const fetchMeta = () => staticFetch("meta.json").catch(() => null);

// ---- Live data (MLB Stats API, called directly from browser) ----
export const fetchTodayGame = async (teamId) => {
  const today = new Date();
  const endDate = new Date(today);
  endDate.setDate(endDate.getDate() + 14);

  const fmt = (d) => d.toISOString().split("T")[0];

  try {
    // Check today first
    const todayResp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1, teamId, date: fmt(today),
        hydrate: "team,linescore,probablePitcher", gameType: "R",
      },
    });

    const todayGames = todayResp.data.dates?.[0]?.games || [];

    // Live or scheduled game today
    const liveOrScheduled = todayGames.find((g) =>
      ["In Progress", "Scheduled", "Pre-Game", "Warmup"].includes(g.status?.detailedState)
    );
    if (liveOrScheduled) return formatGame(liveOrScheduled, true);

    // Final game today - also find next game
    const finalGame = todayGames.find((g) => g.status?.detailedState === "Final");

    // Get upcoming games
    const futureResp = await mlbApi.get("/schedule", {
      params: {
        sportId: 1, teamId, startDate: fmt(today), endDate: fmt(endDate),
        hydrate: "team,linescore,probablePitcher", gameType: "R",
      },
    });

    const allDates = futureResp.data.dates || [];
    let nextGame = null;
    for (const dateEntry of allDates) {
      const gameDate = new Date(dateEntry.date + "T00:00:00");
      if (gameDate <= today) continue;
      if (dateEntry.games?.length) {
        nextGame = dateEntry.games[0];
        break;
      }
    }

    if (finalGame) {
      const result = formatGame(finalGame, false);
      result.nextGame = nextGame ? formatGame(nextGame, true) : null;
      return result;
    }

    if (nextGame) return formatGame(nextGame, true);
    return { noGame: true, message: "No games scheduled in the next 14 days." };
  } catch (e) {
    console.error("Failed to fetch game:", e);
    return { noGame: true, message: "Unable to load game data." };
  }
};

export const fetchHotPlayers = () =>
  Promise.resolve([]); // Requires pybaseball, not available client-side

export const fetchBvP = async (batterId, pitcherId) => {
  try {
    const bvp = await staticFetch(`players/${batterId}/bvp.json`);
    return bvp[String(pitcherId)] || { pa: 0 };
  } catch {
    return { pa: 0 };
  }
};

export const fetchPitchTypeMatchup = () => Promise.resolve([]);

export const fetchParkHistory = async (teamId) => {
  // Compute from static schedule data
  try {
    const abbr = teamId == 136 ? "SEA" : "ATL";
    const schedule = await staticFetch(`teams/${abbr}/schedule.json`);
    const finals = schedule.filter((g) => g.status === "Final");
    const wins = finals.filter((g) => {
      const isHome = g.home.id == teamId;
      return isHome ? g.home.isWinner : g.away.isWinner;
    }).length;
    const losses = finals.length - wins;
    return { wins, losses, winPct: finals.length > 0 ? round3(wins / finals.length) : null, recentGames: [] };
  } catch {
    return { wins: 0, losses: 0, recentGames: [] };
  }
};

export const fetchPriorMatchups = async (team1, team2) => {
  // Compute from static schedule data
  try {
    const abbr = team1 == 136 ? "SEA" : "ATL";
    const schedule = await staticFetch(`teams/${abbr}/schedule.json`);
    const matchups = schedule.filter((g) => {
      return g.status === "Final" && (g.away.id == team2 || g.home.id == team2);
    });
    const wins = matchups.filter((g) => {
      const isHome = g.home.id == team1;
      return isHome ? g.home.isWinner : g.away.isWinner;
    }).length;
    return {
      games: matchups.map((g) => ({
        gamePk: g.gamePk, date: g.gameDate,
        homeAbbr: g.home.abbreviation, awayAbbr: g.away.abbreviation,
        homeScore: g.home.score, awayScore: g.away.score,
        won: g.home.id == team1 ? g.home.isWinner : g.away.isWinner,
      })),
      record: { wins, losses: matchups.length - wins },
    };
  } catch {
    return { games: [], record: { wins: 0, losses: 0 } };
  }
};

function round3(n) { return Math.round(n * 1000) / 1000; }

// ---- Helpers ----
function formatGame(g, isNext) {
  const away = g.teams?.away || {};
  const home = g.teams?.home || {};
  const at = away.team || {};
  const ht = home.team || {};

  return {
    gamePk: g.gamePk,
    gameDate: g.gameDate || "",
    status: g.status?.detailedState || "",
    isNextGame: isNext,
    venue: { id: g.venue?.id, name: g.venue?.name || "" },
    away: {
      id: at.id, name: at.name || "", abbreviation: at.abbreviation || "",
      score: away.score,
      probablePitcher: extractPitcher(away.probablePitcher),
      logoUrl: `https://www.mlbstatic.com/team-logos/${at.id}.svg`,
    },
    home: {
      id: ht.id, name: ht.name || "", abbreviation: ht.abbreviation || "",
      score: home.score,
      probablePitcher: extractPitcher(home.probablePitcher),
      logoUrl: `https://www.mlbstatic.com/team-logos/${ht.id}.svg`,
    },
  };
}

function extractPitcher(p) {
  if (!p) return null;
  return {
    id: p.id,
    fullName: p.fullName || "",
    photoUrl: `https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/w_213,q_auto:best/v1/people/${p.id}/headshot/67/current`,
  };
}
