import os

MLB_API_BASE = "https://statsapi.mlb.com/api/v1"
MLB_PHOTOS_BASE = "https://img.mlbstatic.com/mlb-photos/image/upload"

ALLOWED_TEAM_IDS = {108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 158}

TEAM_META = {
    108: {
        "name": "Los Angeles Angels",
        "abbreviation": "LAA",
        "venue_id": 1,
        "venue_name": "Angel Stadium",
        "league": "AL",
        "division": "AL West",
        "division_id": 200,
        "primary_color": "#BA0021",
        "secondary_color": "#003263",
        "accent_color": "#862633",
    },
    109: {
        "name": "Arizona Diamondbacks",
        "abbreviation": "AZ",
        "venue_id": 15,
        "venue_name": "Chase Field",
        "league": "NL",
        "division": "NL West",
        "division_id": 203,
        "primary_color": "#A71930",
        "secondary_color": "#E3D4AD",
        "accent_color": "#000000",
    },
    110: {
        "name": "Baltimore Orioles",
        "abbreviation": "BAL",
        "venue_id": 2,
        "venue_name": "Oriole Park at Camden Yards",
        "league": "AL",
        "division": "AL East",
        "division_id": 201,
        "primary_color": "#DF4601",
        "secondary_color": "#27251F",
        "accent_color": "#000000",
    },
    111: {
        "name": "Boston Red Sox",
        "abbreviation": "BOS",
        "venue_id": 3,
        "venue_name": "Fenway Park",
        "league": "AL",
        "division": "AL East",
        "division_id": 201,
        "primary_color": "#BD3039",
        "secondary_color": "#0C2340",
        "accent_color": "#FFFFFF",
    },
    112: {
        "name": "Chicago Cubs",
        "abbreviation": "CHC",
        "venue_id": 17,
        "venue_name": "Wrigley Field",
        "league": "NL",
        "division": "NL Central",
        "division_id": 205,
        "primary_color": "#0E3386",
        "secondary_color": "#CC3433",
        "accent_color": "#FFFFFF",
    },
    113: {
        "name": "Cincinnati Reds",
        "abbreviation": "CIN",
        "venue_id": 2602,
        "venue_name": "Great American Ball Park",
        "league": "NL",
        "division": "NL Central",
        "division_id": 205,
        "primary_color": "#C6011F",
        "secondary_color": "#000000",
        "accent_color": "#FFFFFF",
    },
    114: {
        "name": "Cleveland Guardians",
        "abbreviation": "CLE",
        "venue_id": 5,
        "venue_name": "Progressive Field",
        "league": "AL",
        "division": "AL Central",
        "division_id": 202,
        "primary_color": "#00385D",
        "secondary_color": "#E50022",
        "accent_color": "#FFFFFF",
    },
    115: {
        "name": "Colorado Rockies",
        "abbreviation": "COL",
        "venue_id": 19,
        "venue_name": "Coors Field",
        "league": "NL",
        "division": "NL West",
        "division_id": 203,
        "primary_color": "#33006F",
        "secondary_color": "#C4CED4",
        "accent_color": "#000000",
    },
    116: {
        "name": "Detroit Tigers",
        "abbreviation": "DET",
        "venue_id": 2394,
        "venue_name": "Comerica Park",
        "league": "AL",
        "division": "AL Central",
        "division_id": 202,
        "primary_color": "#0C2340",
        "secondary_color": "#FA4616",
        "accent_color": "#FFFFFF",
    },
    117: {
        "name": "Houston Astros",
        "abbreviation": "HOU",
        "venue_id": 2392,
        "venue_name": "Minute Maid Park",
        "league": "AL",
        "division": "AL West",
        "division_id": 200,
        "primary_color": "#002D62",
        "secondary_color": "#EB6E1F",
        "accent_color": "#F4911E",
    },
    118: {
        "name": "Kansas City Royals",
        "abbreviation": "KC",
        "venue_id": 7,
        "venue_name": "Kauffman Stadium",
        "league": "AL",
        "division": "AL Central",
        "division_id": 202,
        "primary_color": "#004687",
        "secondary_color": "#BD9B60",
        "accent_color": "#FFFFFF",
    },
    119: {
        "name": "Los Angeles Dodgers",
        "abbreviation": "LAD",
        "venue_id": 22,
        "venue_name": "Dodger Stadium",
        "league": "NL",
        "division": "NL West",
        "division_id": 203,
        "primary_color": "#005A9C",
        "secondary_color": "#EF3E42",
        "accent_color": "#A5ACAF",
    },
    120: {
        "name": "Washington Nationals",
        "abbreviation": "WSH",
        "venue_id": 3309,
        "venue_name": "Nationals Park",
        "league": "NL",
        "division": "NL East",
        "division_id": 204,
        "primary_color": "#AB0003",
        "secondary_color": "#14225A",
        "accent_color": "#FFFFFF",
    },
    121: {
        "name": "New York Mets",
        "abbreviation": "NYM",
        "venue_id": 3289,
        "venue_name": "Citi Field",
        "league": "NL",
        "division": "NL East",
        "division_id": 204,
        "primary_color": "#002D72",
        "secondary_color": "#FF5910",
        "accent_color": "#FFFFFF",
    },
    133: {
        "name": "Oakland Athletics",
        "abbreviation": "ATH",
        "venue_id": 10,
        "venue_name": "Oakland Coliseum",
        "league": "AL",
        "division": "AL West",
        "division_id": 200,
        "primary_color": "#003831",
        "secondary_color": "#EFB21E",
        "accent_color": "#A2AAAD",
    },
    134: {
        "name": "Pittsburgh Pirates",
        "abbreviation": "PIT",
        "venue_id": 31,
        "venue_name": "PNC Park",
        "league": "NL",
        "division": "NL Central",
        "division_id": 205,
        "primary_color": "#27251F",
        "secondary_color": "#FDB827",
        "accent_color": "#FFFFFF",
    },
    135: {
        "name": "San Diego Padres",
        "abbreviation": "SD",
        "venue_id": 2680,
        "venue_name": "Petco Park",
        "league": "NL",
        "division": "NL West",
        "division_id": 203,
        "primary_color": "#2F241D",
        "secondary_color": "#FFC425",
        "accent_color": "#A0AAB2",
    },
    136: {
        "name": "Seattle Mariners",
        "abbreviation": "SEA",
        "venue_id": 680,
        "venue_name": "T-Mobile Park",
        "league": "AL",
        "division": "AL West",
        "division_id": 200,
        "primary_color": "#0C2C56",
        "secondary_color": "#005C5C",
        "accent_color": "#C4CED4",
    },
    137: {
        "name": "San Francisco Giants",
        "abbreviation": "SF",
        "venue_id": 2395,
        "venue_name": "Oracle Park",
        "league": "NL",
        "division": "NL West",
        "division_id": 203,
        "primary_color": "#FD5A1E",
        "secondary_color": "#27251F",
        "accent_color": "#EFD19F",
    },
    138: {
        "name": "St. Louis Cardinals",
        "abbreviation": "STL",
        "venue_id": 2889,
        "venue_name": "Busch Stadium",
        "league": "NL",
        "division": "NL Central",
        "division_id": 205,
        "primary_color": "#C41E3A",
        "secondary_color": "#0C2340",
        "accent_color": "#FEDB00",
    },
    139: {
        "name": "Tampa Bay Rays",
        "abbreviation": "TB",
        "venue_id": 12,
        "venue_name": "Tropicana Field",
        "league": "AL",
        "division": "AL East",
        "division_id": 201,
        "primary_color": "#092C5C",
        "secondary_color": "#8FBCE6",
        "accent_color": "#F5D130",
    },
    140: {
        "name": "Texas Rangers",
        "abbreviation": "TEX",
        "venue_id": 5325,
        "venue_name": "Globe Life Field",
        "league": "AL",
        "division": "AL West",
        "division_id": 200,
        "primary_color": "#003278",
        "secondary_color": "#C0111F",
        "accent_color": "#FFFFFF",
    },
    141: {
        "name": "Toronto Blue Jays",
        "abbreviation": "TOR",
        "venue_id": 14,
        "venue_name": "Rogers Centre",
        "league": "AL",
        "division": "AL East",
        "division_id": 201,
        "primary_color": "#134A8E",
        "secondary_color": "#1D2D5C",
        "accent_color": "#E8291C",
    },
    142: {
        "name": "Minnesota Twins",
        "abbreviation": "MIN",
        "venue_id": 3312,
        "venue_name": "Target Field",
        "league": "AL",
        "division": "AL Central",
        "division_id": 202,
        "primary_color": "#002B5C",
        "secondary_color": "#D31145",
        "accent_color": "#B9975B",
    },
    143: {
        "name": "Philadelphia Phillies",
        "abbreviation": "PHI",
        "venue_id": 2681,
        "venue_name": "Citizens Bank Park",
        "league": "NL",
        "division": "NL East",
        "division_id": 204,
        "primary_color": "#E81828",
        "secondary_color": "#002D72",
        "accent_color": "#FFFFFF",
    },
    144: {
        "name": "Atlanta Braves",
        "abbreviation": "ATL",
        "venue_id": 4705,
        "venue_name": "Truist Park",
        "league": "NL",
        "division": "NL East",
        "division_id": 204,
        "primary_color": "#13274F",
        "secondary_color": "#CE1141",
        "accent_color": "#EAAA00",
    },
    145: {
        "name": "Chicago White Sox",
        "abbreviation": "CWS",
        "venue_id": 4,
        "venue_name": "Guaranteed Rate Field",
        "league": "AL",
        "division": "AL Central",
        "division_id": 202,
        "primary_color": "#27251F",
        "secondary_color": "#C4CED4",
        "accent_color": "#FFFFFF",
    },
    146: {
        "name": "Miami Marlins",
        "abbreviation": "MIA",
        "venue_id": 4169,
        "venue_name": "loanDepot park",
        "league": "NL",
        "division": "NL East",
        "division_id": 204,
        "primary_color": "#00A3E0",
        "secondary_color": "#EF3340",
        "accent_color": "#41748D",
    },
    147: {
        "name": "New York Yankees",
        "abbreviation": "NYY",
        "venue_id": 3313,
        "venue_name": "Yankee Stadium",
        "league": "AL",
        "division": "AL East",
        "division_id": 201,
        "primary_color": "#003087",
        "secondary_color": "#E4002C",
        "accent_color": "#C4CED4",
    },
    158: {
        "name": "Milwaukee Brewers",
        "abbreviation": "MIL",
        "venue_id": 32,
        "venue_name": "American Family Field",
        "league": "NL",
        "division": "NL Central",
        "division_id": 205,
        "primary_color": "#FFC52F",
        "secondary_color": "#12284B",
        "accent_color": "#FFFFFF",
    },
}

# Cache TTLs in seconds
CACHE_TTL_ROSTER = 86400       # 24 hours
CACHE_TTL_TEAM_INFO = 604800   # 7 days
CACHE_TTL_SCHEDULE = 3600      # 1 hour
CACHE_TTL_TODAY = 900          # 15 minutes
CACHE_TTL_STANDINGS = 3600     # 1 hour
CACHE_TTL_PLAYOFFS = 21600     # 6 hours
CACHE_TTL_PLAYER_STATS = 3600  # 1 hour
CACHE_TTL_STATCAST = 86400     # 24 hours
CACHE_TTL_HOT_PLAYERS = 21600  # 6 hours

FRONTEND_ORIGIN = os.getenv("FRONTEND_ORIGIN", "http://localhost:5173")


def get_current_season() -> int:
    """Return the current MLB season year. Before March, return previous year."""
    from datetime import date
    today = date.today()
    if today.month < 3:
        return today.year - 1
    return today.year
